export const old_proverbs = ["Abûr daye ebûrê. ",
"Adar e meşka li dar e, ne li hera, li beriya Sîngor e. ",
"Adar e, dew li dar e,	şivanî xwe mal e, kebanî bi kar û bar e. ",
"Adar e, dew li dar e. ",
"Adar e berf giha guliyê dar e, nema danê êvar e. ",
"Afirê gameşa bû warê gelşe mêşa. ",
"Agir berda komê, xwe da feza zomê. Agir li ber piyên wî dibe av. ",
"Agir berda kayê, xwe da ber bayê. Agir berda malê, revî xwe da palê. Agir davêje devê xwe. ",
"Agir girte mala yekî, yê din got: “Tu bi Xwedê kî ne vemirîne, da ku (ez) kewên xwe li ber bibirêjim.'' Agir girtibû mala yekî, yekî jî ser û   pe li ber dikizirandin. Agir ji dawê dibare.",
"Agir bi dawê ketiye. Agir ji dev dibare. ",
"Agir bi mala derewînan ket, kesî jê bawer ne kir. ",
"Agir bi mala yekî ketibû, yekî jî li ber firikê xwe diqelandin. ",
"Agir bi serê min ketiye, tu jî li ber rûnê xwe diqijirînî. ",
"Agir pêkeve bîhna bîso jê na hê. Agirê bin kayê ye. ",
"Agirê xweş, agirê darê hişk. ",
"Aha Gule bihar, aha Gule zivistan. Alikî sîn e, alîkî sahî ye. ",
"Aliye xwede je stendiye. Amanet heta qiyamet. ",
"An barek derew, an barek dirav. An hero, an mero. ",
"An mam, an xal. ",
"An naçe as, an jî diçe asvan dikuje. An naçe diziye, an jî diçe sivan   dikuje. ",
"An nane te genim, an zare te genim. Anî ji deriyan, da xera miriya. ",
"Ape sorvirçî, ji deste wî gurî derket kete deste wî hirçî.",
"Apke (Ape) Faris, niha tu nemirî tuye beyî nav garis! Apo ne gej e, tistan dizane (dibîne) nabeje. ",
"Aqil bi dînan çi bike, çav bi koran çi bike. ",
"Aqil je birîn. ( Aqil je nahbire.) Aqil le buye av. ",
"Aqil sivik e, ling çapal e. Aqile kew re, risqe bihare Aqile kurî caniya del..",
"Aqile kurî, bi teyran re firî. Aqile kurî, se te da birî. ",
"Aqile min dibire, aqile gilika min nabire. ",
"Aqile wî/we di nav çoken wî/we da ye. ",
"Aqile xwe bi nan u dew ve xwariye. ",
"Aqile xwe bide sere xwe. (Topî sere xwe ke.) Ar u pelur e, xuy (xwedî) qebul e. Are (Arde) xwe pehtî ye, kapeka xwe retiye. ",
"Are hur di hewana xwe de dîtiye. Are kewan e, risqe betan e. ",
"Are keware risqe bihare. ",
"As berdaye, pey çeqçeqe ketiye. As bi xeyalekî, asvan bi xeyalekî. As digere, çeqçeq dirane xwe diskene. ",
"As ji dest çuye, pirsa çeqçeqe dike. Asek nehistiye ku, arvane xwe le ke. Av bisekine, ew nasekine. ",
"Av gewriye, gewrî xeniqî. Av li dev dikeve. ",
"Av li Nerwane, feyde li Taqwane. Av nade guzike. ",
"Av pe germ dibe. ",
"Av rabu, sirik (bend) bela bu. Ava bîra bi tedbîra. ",
"Ava heft girara li dev çu. (diçe)   Ava sare, ser çi da diçî xware. ",
"Ava ser beruya, wek zavaye bi dile xesuya. ",
"Ava zimzim, li pey dibezim. Ave da nave. ",
"Ave ku da serî, çi bohistek çi çar tilî. Ave selî dike.",
"Avek (kel) kelandî ser da kir. Avek sar di ser da vexwar. ",
"Avek sar ser da kir. Avete pas guhe xwe. Avriyen tirs daveje. ",
"Ax u avayî nav u nandayî. ",
"Axa gote Mirtib: “Eze te xim“ . Mirtib got “Axaye min eze runim.“ Axa ji xulame xwe re got, xulam ji kuçike xwe re got, kuçik jî ji dela (teriya) xwe re got. ",
"Axa li kefe ye, mal maye li bin berfe ye. ",
"Axa li kefe ye, xulam di nav zicre ye. Axaye be xulam e. ",
"Axaye me Bil e xwere me ser kul e. ",
"Axaye me bu Pilo, sîva kere me bu çilo. ",
"Axaye me Om e, xwelî li sere me kom e. ",
"Axaye min wax çave min kor bin ji bo hespe boz. ",
"Axayî bi xulam e, xulamî bi olam e. ",
"Ba dere wî/we digire, ba vedike. Ba ji zinar (teht) çi dibe? Ba vî alî dixe, wî alî re debas dike. Baçelmok (bi) sev digerin. ",
"Bajarî, li erde  narî. Ban qul e, binban sil e. ",
"Bane me yek ban e, yalik dest e, yek zozan e. ",
"Banek e u bagurdanek e. Bar ji ser xwe daveje. ",
"Bar min naesîne, serbar min desîne. Bar naçe ber kerî, ker diçe ber barî. Baran disekine pey da (du re) ga cil dike. ",
"Barana havîna, sil kir bine kulîna. Barane erd sil kir, zîpike erd qul kir. Bare kere li ser pista deve ye. ",
"Bare xwe girtiye. ",
"Barek dirav, yan barek derew? Barek quran sond bixwe, kes je bawer nake. ",
"Bav harsim dixwe, diranen kur disekihin. ",
"Bav ji es te, kur je pirsa bajer dike. Bav ji es te, kur saloxan dide. ",
"Bav kustiye (ku) gore sond dixwe. (bixwe) Bav rezek da law, law guslek tirî neda bav. ",
"Bavo hun çima ker ker xebernadin? Bavo, min bivirek dît. Got: “kane?“ Got: “Min winda kir.“ Baye hewana wî li ber çu. ",
"Baz bi bazan, qaz bi qazan, mirîska kor bi dîke kulek ra. ",
"Be are ji çi ar bike, we kume xwe tim xwar bike. ",
"Be male, malxe male, neye male qeda sale. ",
"Be malo, be xatî be xalo; bi malo, bi xatî bi xalo. ",
"Be serî u be binî (ye). Be zar u be ziman (e). ",
"Bedewe çav kil kir, dile xortan tev kul kir. ",
"Bedewe here, xer ji bazara te naye! Behra sîn e, av te de nîn e. ",
"Beje beje zimane te direj e. ",
"Beje min hevale xwe ez bejim tu kî yî? Bejin biriqî, dil xeriqî. ",
"Bejn lal e, (bila) nebejin tiral e. Bejn tît e, mal mecît e. ",
"Bejn zer e, dil jehr e. ",
"Bejna heyrane her kiras le te. Bejna min sehr e, dile min jehr e. Bela li sere (xwe) wî/ we vekir. ",
"Bela xelke ji çol u çiyan te, ya min belengaze Xwede ji ber lingen min te. ",
"Bela xwe je venake. Bela xwe le digerîne. ",
"Belaye newe newe, dema tu hatî li ser sera u li ser herdu çavan. ",
"Belaye! Çaven res u belek min ji te re kildan e. ",
"Belengaze aqile xwe ye. Belengaze Xwede ye. ",
"Benamuse ulme (ilme) xwe ye! Bendera ku çelek ser bigere, ew çi bender e? Bendike Ruto dudu ne, çave wî li min çave min jî li yekî (yeka) din e. Benîste xwe cu ye, li netika xwe ve daniye. ",
"Beqe çav da çeleke, zike we teqiya. Ber barane revî, li zîpike qelibî. ",
"Ber barene revîm, ber çortane ketim. Ber defa be deng direqise. ",
"Ber defa cuna direqise. Ber ecela xwe ve diçe. ",
"Ber ecele xwe direve. ",
"Ber goste çuyî nakeve, ber serpiyan   dikeve. ",
"Ber kere re derbaz dibe, cehsike je didize. ",
"Ber li serî, yan serî li ber (î), her serî we biske. ",
"Berda sond dixwe. Berdana jine, edeta dine. ",
"Bere dest destan diso, pase dest serçavan diso. ",
"Bere merezî bu îja terese jî lexist. Bere pir bi gul bu, barane lexist sil bu. ",
"Berf hatiye ku ling (de) bicemide. Berf heliya, ling wesiya. ",
"Berf jî spî ye, le kuçik di ser da pîsiye xwe dikin (dirîn). ",
"Berf jî spî ye, le tam le tune ye. ",
"Berî barane ba ye, berî mirine ta ye. Beru da bizine, dest avete qarçike. ",
"Beru ji qalike xwe banzda u got: “Magî devî çawa ye!“ Berxik spartine gur. ",
"Bes hat sere maldaran, avetin sere   feqiran. (jaran) Bexdaye jî xurme zef in, ji me re çi ye? Bexte pesîn, ware hesîn. (Bext bexte pesîn war ware hesîn.) Beyî derî ji te ra vekiriye, heri re ji te ra vekirî ye. ",
"Beyî mala me te bibînî hale me. Bez spartiye pisîke. ",
"Bi ava zemzeme (ve) sustine. Bi çar destan ve girtiye. ",
"Bi çavekî le nenere. ",
"Bi destan da, bi lingan pey ket. (im) Bi destekî nesustî li nav derket. ",
"Bi desten xwe mala xwe xera kir. Bi deve xwe kete belaye. ",
"Bi deve xwe ve napeyive (xebernade) Bi fita Hesene Hewerî. ",
"Bi gur re dixwe, bi xwedî re sîne dike. ",
"Bi gurmiste, dibeze sujine. Bi guye xwe ve buye yek. ",
"Bi heçeta (hinceta) kurke dixwe   virike. ",
"Bi kapekekî Uris nake. ",
"Bi kere nikare dibeze kurtan. ",
"Bi kevçiyan ve da berhev bi hesikan ve bela kir. ",
"Bi kinco, were qunco, bi qerpalo here malo. ",
"Bi kîrekî kulavî le dige. Bi kulme, diçe direje. ",
"Bi min xurto, li min xurto. ",
"Bi penciruka li guye xwe ketiye. Bi piye xwe kete tele. ",
"Bi qîzanî mîr bu, bi jinanî pîr bu. Bi quna ziya filitî. ",
"Bi qune ketiye çala genim. ",
"Bi qune, ketiye kodika jajerune. Bi roj bilbil e, bi sev piskul e. ",
"Bi roj kefene miriyan je dike, bi sev bulqe bulqa kuza ditirse. ",
"Bi roj miriyan diselîne bi sev qurquroneka derî ditirse. ",
"Bi roj ronahî li ber min neke. Bi ruyekî spî je xilas bum. ",
"Bi sere poz xeberdide. ",
"Bi sev sememok e, bi roj pîrebok e. Bi tekbîr, dikolin bîr. ",
"Bi tepa li sere xwe ket.  Bi ve qune, tu naçî sune. ",
"Bi ve qune, tu naxwî hekerune. Bi ve quse, tu naçî Muse. ",
"Bi vî hisî, tu nagihejî tu par u pisî. Bi viran sond bixwe serî naese. ",
"Bi xera kîre min (çike min) buye mîre min. ",
"Bi xwe bume dize sola xwe. ",
"Bi xwe pir gul bu, barane lekir sil bu. ",
"Bi xwîna xwe xeber dide. ",
"Bibe nebe mirov goste kewana jî dixwe. ",
"Biçe Bitlîs, we bilîz. ",
"Biçe ser kahniye, kahnî we ziya bibe. ",
"Bîhn le çikandin. Bîhna biso je te. ",
"Bîhna ceheneme ji dev te. ",
"Bîhna kiz te ji mala diz. Bîhna sîr ji dev te. ",
"Bihusta ku ez ne te de bim (ne le bim) bila ker te de vegevizin. ",
"Bila avis be, kenge dize bila bize. Bila bejin xençera Xaço heye. ",
"Bila ev jî daxek be li deste min be. Bila hindik, bila rindik. ",
"Bila jina mere çe bim, bila roje heft caran sere min be sikandin. ",
"Bila kuçike gunda bim, ne piçuke bira bim. ",
"Bila kuçike sa bim, ne piçuke bira bim. ",
"Bila kuleka te du negire. ",
"Bila li xwede xwes here, bila li evdan xwes neçe. ",
"Bila me be, sîr qismet e. ",
"Bila mere min mer be, bila sere min li ser tera er be. ",
"Bila ne di min da be, bila di diya min da be. ",
"Bila ne li ber agire min be, bila ber   agire mala bave min be. ",
"Bila razana te hebe, rabuna te tune be. ",
"Bila reze min li nav rezan be, bila tirî li min heram be. ",
"Bila sure xweyî tuj baveje quzika min. ",
"Bila tu gurbiyayî bila te bere kera min bixwara. ",
"Bila tu xwes bî, gula siwara bî. Bila xwes bî, gula govenda bî. ",
"Bila ya dehan ji li ser ya nehan be. Bila zike mela bel be, bila gîha u pel be. ",
"Bilbil xistine qefesa zerin, gotiye: “Ax welate min.“ Bilbil xistine qefesa zerin. Got: “Ka gula mina bi bîhn?“ Bilind firiya, nizim ket. Bin ga da golikan digere. Biratî, bi rastî. ",
"Biraye ji de ye, silava dide li pe ye; ew jî ji bo lome xelke ye. ",
"Birayek din, yek hisyar, dan muyeke neqetandin. ",
"Birçî bu ter nabe, ter bu birçî nabe. Birîna hevalan, tîra kendalan. ",
"Birîna min, min keder te. ",
"Birîna sura kurtir, birîna sura heye. Birîne diherisine. ",
"Bivirvan dar birî, ye li ser dare guman ji xwekde nebirî. ",
"Bixwî çavekî min, nexwî derdu çaven min. ",
"Biyanî bidî goste canî, we li ser te de bet posmanî. ",
"Biye kevçî xwîn, ketiye pesa min. Bizanibe giliya, welat xwestir e ji hemiya. ",
"Bizin bizin e, bere cîhe xwe pekol dike du re mexel te. ",
"Bizin firot bi hefta, beze we kirî bi heysta. ",
"Bizin ketiye derde sere xwe, sivan ketiye derde beze bizine. ",
"Bizin mir, gir damirî. ",
"Bizina kol elimiye danukan. ",
"Bizina kol, hîn bu (ye) daniyen sor. Bizina kulek u sivane bezek (sivik) tev digehen ber derî. ",
"Bizina nehletî, dev leketî. Bizina res e, her roj nexwes e. Boçik ketiye nav lingan. ",
"Boçika wî dixure. Boçika wî ketiye qune. Boçika xwe ba dike. ",
"Boçika xwe bilind digire. Bu (ye) destare kizina. ",
"Bu çala bi derziye. (vedayî) Bu gur, hef golik jî xwarin. Bu mesal xal u xwarzî. ",
"Buk bi dile zave ye. ",
"Buk di sorike de, dergus di lorike de. ",
"Buk li hespe ye, hefsar li miste ye, kes nizane qismete ke ye. ",
"Buk ma heviya baltuze (dise) dile we bu kela dîze. ",
"Buka ape kete kape, buka xale   delaliya male. ",
"Buka male, qesmera male. Buka xale ezîza male.",
"Buke (buka ku) xeniqandiye heft xesî, ji bulqiniya cer ditirsî. ",
"Buke pe pepar, sivan (o) dar gopal. Buke tune zar-ziman, xesuye tune dîn-îman. ",
"Bume gaye dîz-kiloza. ",
"Bune dîk u mirîsk li ber hev sekinîne. ",
"Buxza wî buxza deva ye. Buye ava bin kaye. ",
"Buye bereta li ser berata. Buye buka barane. ",
"Buye cirm ketiye hustiye min. Buye çeleka sor, sîre xwe dide dawiye de linge xwe ledixe direje. Buye çira ber kora. ",
"Buye çiyaye Sîpane, sere xwe danaxwe. (natewîne) Buye dasiye masiye. Buye defa ber kera. ",
"Buye diware ser buze. Buye dîzika Behlul. ",
"Buye Eliye xem xwar. Buye findiqa ser nergize. ",
"Buye gaye cot, ne kisî mese ser xwe dike ne ji ye ciranan. ",
"Buye gola reqe (u) beqan. Buye hîva bin ewr. ",
"Buye keleme ber çavan. ",
"Buye kere Bute, yek salî bu du kel hilgirt, du salî bu kelek hilgirt. ",
"Buye kevir, xwîn je naye Buye kewa dafike. ",
"Buye male mirî. ",
"Buye mesela jinik u meqese. Buye mesela masiyen sove. ",
"Buye mîza seytîn. (dipeke her dere) Buye nivista mele. ",
"Buye qîza qurqur bege. Buye riya kadize. ",
"Buye roviye ji mirîskan xwe re mezin buyî. ",
"Buye serikî kera. ",
"Buye tajiya kuça. Buye xesuya seyan. ",
"Buye xweya hemi giraran.",
"Ca (ce) nalekî (hesinekî) bavejin ber linge wî/ we. ",
"Ca bihelin ez jî anaxazeke biherim. Cano min tu danî, kesî tu hilneanî. Car caran tîne, gaye res baran tîne. Careke te bixapîne ar di mala wî keve; bu di cara, du caran ar di mala wî keve; ku bu se caran ar di mala te keve. ",
"Carina dibe kura kirece, carina dimbe dîware buze. ",
"Carina dimis-run e, carina qetil- xwîn e. ",
"Carina mirov ji mecburî goste kewan jî dixwe. ",
"Carina mirov ji yare diya xwe re debeje “bavo“. ",
"Caw bu kitan, dew bu derman. Cawa (bersiva) wî kire dest. ",
"Cawe sil firotine. ",
"Ceger le sewitî ye. (sotiye) Cegere be mefere bira kustin (mire) neçu sere. ",
"Cem mîhe çave berxe derdixe. Cer nu ye, av cemidî ye. ",
"Cîhe be def direqise, ma dora cîhe bi def. ",
"Cila sil e, ketiye mil e. Cila xwe ji ave derdixe. ",
"Cile u kulev ji hev dipiskeve. Cilen xwe sil kir beriya barane. Ciwan mîse ne , bele xwîn serîn u kit-kite ne. ",
"Ciwanekî bavejin resiya pîreke bavejin xwesiya. ",
"Ciye jina xera kiriye, hînava ye. Ciye ku pakî le heye, xirabî çi ye? Ciye seran rovî dikin geran. ",
"Cote xwe daye kevir. ",
"Cottar li bervî mal e, kebanî nu bervî kar e. ",
"Cotyaro ew çiye tu diçînî? Got: “Dema hesîn bu te bibînî.“ Cucan: Gundekî Gîhadîna giredayî Agiriye ye. ",
"Cuhî da (ka) te bibim buhiste. Got: “Ne îro semî ye, ker naye.“ Cun le taste kirine. (kirin) Ç ….",
"Çar çav (buye.) Çar gurçikî (ye.) Çav birçî (ye.) Çav çavan nabîne. Çav çune ser serî. Çav giredan. ",
"Çav girtî  ye. Çav girtîbun. Çav le derxistin. ",
"Çav le tirsandin. Çav leketin. ",
"Çav sor. ",
"Çav ter. ",
"Çav vekirî. (Çav bel.) Çav wek sekir spî buye. ",
"Çava ji xwe diborîne. (dibuhurîne) Çavan giredide. ",
"Çavan je girtiye. ",
"Çave de u bava li ewladan, çave ewlada li çiyaye Qaf. ",
"Çave hev derdixin. ",
"Çave li deriya, xwelî li seriya. Çave min î kor nenere, bexte min binere. ",
"Çave we/ wî le bar nabe. Çave xwe kutaye destan. ",
"Çavek kor be, mirov deste xwe dide ber ye din. ",
"Çaven we/ wî je dibire. Çaven we/ wî je girtiye. Çaven we/ wî ter nabin. ",
"Çaven wî/ we res bune. (kor bune)   Çaven wî/ we tistekî nabînin. Çaven xwe belle vedike. ",
"Çaven xwe je re diçirîne. (diqelisîne) Çaven xwe zoq kirine. ",
"Çavresiyan dike. ",
"Çawa direse, wulo badide. Çawa suk e, gaz piçuk e? Çawa suk e, wisa jî buk e. ",
"Çaxe neçîra min te, guye tejiya min te. ",
"Çaxe piçuk bum ji mezinan ditirsiyam mezin bum ji piçukan ditirsim Çel u dotin, kezwan u kelotin ne vek ketiye. ",
"Çeleka me avis be we rojeke bize. Çeleke didose Xate, to dixwe Fate. Çeleke rex kiriye di ser destiye bivir de. ",
"Çem tim naye qirs u qal li ber naye. Çeme Mirade çiqasî rabe, nikare tistekî ji quling bike. ",
"Çend nîsk ji serî kem in.",
"Çend texte ji serî kem in.",
"Çerme golike li ber me we xwedî be li ser me. ",
"Çi buyî kundir, çi jî hustiye te direj- bu. ",
"Çi di hur de, çi di tur de. Çi giriya ku çi jî beecî? Çi xwar ku çi jî pe veresî? Çi zu buyî kundir, te çi zu sax veda? Çilkek, milkek. ",
"Çima buye kerta kevir? Çima guye xwe xwariye? Çima ji min mîh u meîn mane? Çima razem newala kur, çima bibînim xewna dur. ",
"Çima rihe xwe kur nakî? Got: “Dile min bi qune ne xwes e.“ Çima seyek nikare, cendedekî bi deve xwe bigire? Çiqas dinya li hev dikeve, tistek ji me re ser dikeve. ",
"Çiqasî li ser erde ye, ew qasî jî li bin erde ye. ",
"Çira ber kora, defa ber kera. Çira xizanî ji nezanî. ",
"Çivîk çivîk e ave vedixwe, li ser xwe re xwede dinere. ",
"Çivîka wîlwîlanî ez kor bum min nizanî, te mala xwe xera kir kone min jî pe re danî. ",
"Çiya naçe, dewres diçe. Çiyî feqîran, derge mîran? Çoken xwe nerm kirin. ",
"Çu bajer u got: “Baba kenger nerede biter?“ Çu dermane mîze, gu le esirî. ",
"Çu gergere, hat dîsa ew kere bere. Çu gunde nenas pesne xwe da be qiyas Çu heyfa bave, quna de jî da ser. Çu kare kar jî nebu, taye jî ket. ",
"Çu Rewane birinc ji saware male jî bu. ",
"Çu ser dare, dara bin xwe birî. ",
"Çuk e diçe li ser heke betan rudine. Çukan xem e, Xabur çem e?   Çuke bira, çelike gura. ",
"Çum li sere çiya, zuriyam weke gura, birazî nabin bira. ",
"Çume derva Fatekor, hatim hundir xatekor. ",
"Çume mala ape xwe ketme kape xwe. ",
"Çume mala dewresa, danî ber min maste gamesa. ",
"Çun dewsa miriya, hemi kes li miriye xwe giriya. ",
"Çun welate kera, anîn bare pera. Çuye tolana (tole bigire) seyda (neçîra) hestiyan digere. ",
"Çuyîn ji me, hatin ji xwede. ",
"Da kes weke wî bi sev kere xwe nagere. ",
"Da tu bizanî (bî) dew biraye mast e. Dane ber bere res. ",
"Dar bir verotine, mirov bi gotine. Dar dikeve, berî bi ku ve? Dar ez dikutim, intîn ji te te. ",
"Dar li kewe neket, kew li dare ket. Dara biye be ker e, ne bistan e, ne ber e. ",
"Dara dixe qula mesa (moza). Darbiro daran bibir, gumana xwe ji xwede nebir. ",
"Dareke digire hezar darî (devî) dihejîne. ",
"Dareke texed quna wî, kulîlkeke dide ber behna wî. ",
"Darî xware, hosteyî rast e. Daro skesto, xwaro besto. Dasek u dehlek? Dawet daweta mîran, agir ketiye feqîran. ",
"Dawet fetikî (fetilî) berbu hetikî. Daweta duduyan e, gire (agire) hemuyane. ",
"Daweta mirtiban be u mirtib lenedin? (le bidin)   Dawiye de ji bo paniya linge xwe erdek hisk dît. ",
"Daye buhike, jine ruhike. ",
"Daye, ewa ku tu dibejî min derda ye. Dayika du dotan, li xwe dide du lotan, ne li vir, ne li Cizîra Botan. ",
"Dayiken dergusan re herin zu vegerin. ",
"De îja (îcar) te girte xwe. ",
"De ka kuma daynin pirsa je bikin.  De li qîze sîret kir, qîze got daye hela tu çîke kere binere çend e. ",
"De u dote ser kirin, kemaqilan je bawer kirin. ",
"Def di desTe min da ye, çomax tu ledixî. ",
"Def u zirne berdaye, bi kendale abes girtiye. ",
"Def ya xelke ye tu çomax ledixî. Defa heware lexistin. ",
"Deh bi duduyan e, Hirmiz xwedane Gololan e. ",
"Deh mal in danzdeh rispiyen wan   hene. ",
"Deh siyar çun pesiya rutekî, rut silamet li nav derket. ",
"Del ba ye, kuçik li pey Bexda ye. Dela xwe daye ser mile xwe. ",
"Delale min ji sîr jî, sekir jî sirîntir e. Dem bi deme re herdem xwede re. ",
"Dema siud hat serî, bila bizire wek kerî, dîsa jî xelke beje aferî. ",
"Demek a gule ye, yek ya sîlane. Deng nekirim, zere zer im. ",
"Denge defe nas dike, mala dawete nas nake. ",
"Denge ezmana, nîsana barana. Denge te xwes te le heke xwendina te quran be. ",
"Dera sor e, çavî kor e. ",
"Derb ku hat serî, xwede we çawa xilas bike? Derbeke li nal dixe, yeke mix (bizmar) dixe. ",
"Derd hatin derda, kul hatin li ser da. ",
"Derdan derevedike. (dereveneke) Derde hewiya, jana tiliya. ",
"Derde wî (ji) girara sibe ye. ",
"Dere sore xwe ba kir, dile xortan tev kul kir. ",
"Derek ava kir, mizgeftek xira kir. Dereweke wan ji deh raste me çetir e. ",
"Derî daye ser piste. ",
"Derî ne berdideyî, kuleke re dikeve hundir. ",
"Dermane her tistî xwe ye, le xwe xirabibe derman çi ye? (derman nîne) Derpiye jine sor e, merî kor e. Derpiye min xwe ke, le te de tir u fisa neke. ",
"Derse degire ji jine, de re dibe dijmine. ",
"Derzî di ber guh re kirin (e). Dest je sustine. ",
"Dest ji cote res berdaye bi zirna zer girtiye. ",
"Dest ji emele wî sar bu. ",
"Dest ji erd u esmana qetiya ye. Dest li ser destan, heya esmane heftan. ",
"Dest nakeve. ",
"Desta dawo, bi piyan li pey geriyawo. ",
"Deste ber derî ye, bikesî we bimerite, nekesî we biherise. Deste de peske qîze. ",
"Deste de reng u ruye qîze. Deste me naye ber deve me. ",
"Deste min di hingir da be cî dihelim tem. ",
"Deste raste dide, bi deste çepe distîne. ",
"Deste sex maç kin, ew sere Qutbe Razî ye; tac u teylesena wî gist xebata deste jar (sar) u tazî ye. ",
"Deste vala, ruye res. ",
"Deste wî tije garis be, livek je narije. Deste wî, ma li ber ruye wî. ",
"Deste wî/ we giran e. ",
"Deste xwe de hekerune çekî u bidî (ye) ewe beje deve min sewitî, deste (wî/ we) te nesewitî. ",
"Deste xwe dixe qula moza. Deste xwe je biso (sustine). Deste zore pîre davejin bîre. Destkuja wî ne helal e. ",
"Desto bi xwe gesto, ha diwesto, ha diwesto. ",
"Dev je berdan (bernedan). Dev jev mayîn. ",
"Dev ji sîr sewitiye, pifî dew dike. Dev ji zirna zer berdaye, bi qula ebcete girtiye. ",
"Dev nerm e pist hisk. ",
"Deva del bi xwar e, piskuleka we jer e, yek li jor e. ",
"Deve bi çerm va dixwe, dile xwe bi mese desîne....",
"Deve dikeve, nav pembu, çaven xwe digire u dibeje: “Kes min nabîne.“ Deve hat bi puleke, pul nabî. ",
"Deve hirçe negihîst seve got: “Çawa   tirs e!“ Deve hîz berdaye, quna hîz girtiye. Deve nal kirin, rovî (jojî) got: “Piye min jî.“ Deve nedît li reze, piskul dît li pireze. (feze) Deve rovî negihîste tiriyan got: “Tirs e.“ Deve te ne deve zirna zer e. Deve te tijî xwîn be, bidî wî/ we nereje. ",
"Deve u gere? Deve wî ne li cem wî ye. (ne li wî ra ye.) Deve wî/ we sist e. (nerm e) Deve xwe daye ber baye geliyan. Deve xwe dide ber deve wî/ we. ",
"Deve xwe guhirand(iye). Devî paç e, zikî xaç e. ",
"Devî zu dibe dar, xwelî li sere ye be war. ",
"Deviye tu dar bî, li ser sere min star bî. ",
"Dew dixwaze, kodike jî vedisere. Dew tirs nîn e, vexwarina hemî benda nîn e. ",
"Dew tune, run difirose. ",
"Dew xwestin u kodik vesartin? Dewe silave, li ber ave. ",
"Dewlet e, bel e, gewr e, bi sev sayî ye, bi roj ewr e. ",
"Dewlet sere axe, tevka hîve. Dewleta lez, rez u pez. ",
"Dewres tîr u direj. ",
"Dewsa sera, kund dikin sera. Dewsa seran, maye kunde dera. Deyn li te (min) caw li xwe kir. ",
"Di aliye xweyî çepe ve rabuye. Di ava wî/ we de diçe (naçe). ",
"Di bin bar de namîne. ",
"Di bin kaye de ave dimesîne. Di dile xwe de disewirîne. ",
"Di firnikan ra anî Di guhe ge de radize. (razaye) Di nav de xeriqiye. ",
"Di nava diranan de buye benîst. ",
"Di nava rune xwe de dihele. ",
"Di navbera min u Xwede de bohistek ma. ",
"Di navbera wan de av derbas nabe. Di navbera wan de çiya hene. ",
"Di orte de dirî li keleke rudine. Di pasila xwe de dikene. ",
"Di pasila xwe de mar xwedî kiriye. Di sîtila dew de muye spî dîtiye. (digere) Di sola wî de av te vexwarin. Di wara da mayî ye. ",
"Di zike xwe de suxule xwe dimesîne. Di zike xwe de xeber dide. ",
"Dibe tu pe re, qeda u bela jî pe re. Dibe xenequtk dikeve gewriya mirov. Dibe, mer be jî, jin be jî bila bize. ",
"Dibe: “Dare das hate te.“ Dibe: “Wekî destî ji min be, min nikare.“ Dibeje le napeje. ",
"Diçe cîhe nenas, pesne xwe dide xas u xas Diçim as as xiradibe, tem kahniye   kanî zuha dibe; ga dikirim dibe golik genim davejim dibe solik. ",
"Dikale le sîr nade. ",
"Dikana Bekiro du qalib sabun u çar kîs xwe. ",
"Dîke min e, li ser kulîlke xelke bang dide. ",
"Dîke yekî winda bu, got li dîken xwe bigerin. ",
"Dîko tu sibehan, evaran dizanî, ma riya bajer nizanî? Dil bune aye sevî, xof, rem ji dine revî. ",
"Dil dixwaze, (le) ji dest naye. Dil germ Dil hildan Dil kevir Dil kirin Dil kirîn Dil li ser dil e, je re tune tu derd u kul e. ",
"Dil mayîn Dil ne sivre ye ku mirov li ber hemî   kesî veke. Dil qewim Dil res Dil sar Dil se Dil stendin Dil sikestin Dil tenik Dil xwes kirin (Dile wî/ we xwes kiriye) Dila pirsî, quna hesilî. ",
"Dile de li ser dote, ye dote li ser çiyaye Qaf. ",
"Dile merik ji jine ne xwes bu, digot: “Tu ard eleg dikî quna xwe ba dikî.“ Dile min ji we (ne) xwes e, erd di bin berfe de res e. ",
"Dile sivan kete piskule (kermekî), hur kir sîr u xwar. ",
"Dile yekî diçu goste kere, digot: “Guhen we wek yen kewroskan e.“ Dile yekî kete kevirekî heft salan bi xwe re gerand. ",
"Dilekî na bi heft dilan. ",
"Dilo bixwaze te boq te pîvaz. Dimirim dibeecim, ceh dibe ez birinc im. ",
"Dimise yekî rijiya, got: “Bila xera bav u diya min be.“ Dîn u îman nan e, nan ku tunebe, bende îro ezdiye, sibe misliman e. Dine ava, em tev nava. ",
"Dine bi dine re, Mendo bi quna dine ve. ",
"Dine ke xwar? Jin u mere ku ji hevdu ra bun yar. ",
"Dine li dine, çave gur li bizine. Dinya buye kes, tu kesî negotiye bes. ",
"Dinya kiriye dara doje. ",
"Dinya li ser guhekî wî/ we ye (ser pelikeka guhe wî/ we ye.) Dinya tev de bisewite, gurzek gîhaye wî nasewite. ",
"Dinya tijî kir be, bostek ji mirov dur be, ma çi kera mirov je heye?   Dinya tijî, mirov te de dijî. Dinya wa hatiye, we wa jî here. Diran es, derman kes. ",
"Dirane xwe disîqîne. ",
"Dirane xwe vesere, se hestiyan digere. ",
"Diranî wî/ we te da çikya ye. (diçike) Direjaya male deh gav, çi bikim mala be nan u be av. ",
"Direse le nikare bide hemberî hev. (hem ber yek bike) Dirika xwe bi deste min dernexe. Dîsa ew tas e, ew hemam e. ",
"Dîsa girara me ji “qet“ a wan çetir e. Dît ez im, nedît diz im. ",
"Dîtina çavan, qinyata dilan. Dîtiya dît, nedîtiya xwe de rît. ",
"Dive ez bejim, kew e, nikil jî sor e? Dîwar tep bu, xubar (toz) rabu. ",
"Dîwaro ji te re dibejim, buke li te eyan be. ",
"Dîwaro min ji te re got, pist diwaro tu guhe xew bide. ",
"Dîwaro, eyb u qusur staro. ",
"Dixwim nan u ave, min mineta kesî nave. ",
"Diya qîza pruda dîza, dîz çekirin, xelke birin. ",
"Diya te ji bo xwede nanekî germ dabu. ",
"Diya te li ser nimeje bu.",
"Diz (î) xwe mal e, derî girtin betal e. Diz ji beroso ra dibeje: “We da here ru teniye!“ Diz u malxe bune yek, ga di bin xeliye de derxistin. ",
"Diz xwediye male girt, du tir ji je berdan. ",
"Diza ji dizan dizî, erd u esman le pirsî. ",
"Diza ji dizan dizî, erd u esman tev lerizî. ",
"Dize da qawe da , çilmezine (çileke, nefseke) ji çila xwe kem nekir. (neda) Dîze got: “Bine min zer e.“ Hesike got: “Le ez ji ku tem?“   Dîzik ji kebaniye ra dibeje: “Ru teniye!“ Dîzike got: “Ez tijî zer im.“ Hesike got: “Min tu hemi seh kirî.“ Dizo, dizo, dizekî be însafo. Dohn e, li eyare sa de ye. ",
"Dohn li çire ke u le ser ke. Done min li sere min dide. ",
"Dono don dixwe, Sondo ber da (ve) sond dixwe. ",
"Dor bi dor e, ne bi zor e. Dost nade, djmin jî naye. Doste qune dijmine serî. ",
"Dotmame ji pismaman fedî kir, dunda li pey xwe nedît. ",
"Doxîn qewîm (sist). Du beru bare kerî. ",
"Du misk ji quleke derketin, yekî ji ye din ra got: “Tu ji kudere teyî?“ Duh ji heke derketiye, îro li mirîske qayîl nabe. ",
"Dupisk tu zivistane ne diyarî. Got: “Pane havîne min gelek ru li ba   hewe heye.“ Dur e, kur e u naye gotin. Dur ve, sirîn ve. ",
"Durî çavan, durî dilan. Duro bi nuro. ",
"Duve xwe di pir tepikan de qurçandiye. ",
"Eceba li ser eceban. (Ew jî eceba li ser eceban e.) Ecela bizine ku te, nane sivîn dixwe. Eger (ku) ez bum keç, ez dizanim ka eze çend gileya bavejim doxîna xwe. Eger bi te xwes e, ji min ra bîst u   ses e. ",
"Eger hewes e, ew jî bes e. Ekla wî je derbas dibe. ",
"Elhodan elhodan, van sex u mela mala me dan.",
"Em (ez) keruska bes in.",
"Em çun Avamesya, delika belek li me hesiya, kula me yek bu, bu   sisiya. ",
"Em ne ji malekene, le li halekîne. Em negihîstin we, ma ku hun bigehejin me. ",
"Eme bikin, heya....",
"Eme bikin, wekî (heya) ro bisekine. Emele pîre nayen bîre. ",
"Emenî birî, ta firî. Emire xwe puç kir. Enî res e, parî xwes e. ",
"Enîska xwe pe nîsan dide. ",
"Erd hisk e, ezman dur e, xwîn je naye. ",
"Erd hisk e, ezman dur e. Erd u ezman hejandin. ",
"Erd u ezman li hev hatin (hatin hev). Erdo veqelise ez tekevime! Ere ere ne, gist (jî) kure kere ne. Ereb u pez, fleh u rez. ",
"Ereba xwe daxist gere. ",
"Erebe çuye dara, hatiye kar e, nehatiye erebe bi xwe dar e. ",
"Erebe ku hatiye ber parte, bila   barke. ",
"Ers u kurs dizanî, çima goste bin birinc nizanî? Erul, bu (bi) kefîle Zerzul. Erzan kirî heban dirî. ",
"Eslî hu, neslî hu. ",
"Ev as e, ev jî çirika as. Ev bar e, ev jî serbar e. Ev dil e, ne bilwxur e. ",
"Ev lele ye, he lolo jî maye. Ev naçe mizgîniya we. ",
"Ev ne suna (cîhe) dewara yeksim e. Ev pîvaza mezin, ev nane genimî ev jî ava cemidî; dîsa jî dibejin Eliye Sino male xwe naxwe. ",
"Ev pîvaza wî ya hesin, ev jî sekire wî ye sipî di nav desmale de; dîsa jî dibejin: “Bave te ji nez de mir.“ Ev riya kin, ev bertila giran, gelo pistî min ke ye bixwe? Ev ruye min, ev ruye te. ",
"Ev ruye te yî sipî, ev ruye min î res. Ev zimane te nubuya, we qijikan   çave te derxistana. ",
"Eva elifbe ye, he pir li pey e. Evdilxebur e ji rehma Xwede dur e, koda wî piçuk e, çirnika wî kur e. ",
"Ew çi sîre te da, ew çi pehna te le da (lexist). ",
"Ew devera ku miske heram bi namus be zanîn Xwede evden xwe ji wir dur bixe. ",
"Ew ezmane ku min dîtiye, baran je naye. ",
"Ew hews e le (bele) ne ew rews e. Ew jî belengaze aqile xwe ye. ",
"Ew jî çilka ji behre zedebuyî ye. Ew ji ew hinde xurt e. ",
"Ew jî eyba li tev eyba vesartiye. ",
"Ew ji qilera dare ye. (Bu qilera dare) Ew jî sewasa li ser sere wî/ we ye. ",
"Ew jî sewasa severesa ye. (Bu sewasa severesa.) Ew jî tutika ru erebe ye. ",
"Ew mirî nakeve ber wî girî. (Ew girî nakeve ber wî mirî)   Ew riya ku te bere xwe daye ez le hatime. ",
"Ew ruhe di wî qalikî re bikise. Ew sal e, le ne ew bihar e. ",
"Ew serî ye, ew oxir e. ",
"Ew tehte ku te ser da rî barane hat sust. ",
"Ew xem bila ji bo we deme be. Ewan girtin heqe xwe, ez mam li reqe xwe. ",
"Ewî ku got res e, tu bibeje spî ye. Ewî ku got sibeh e, tu beje evar e. Eyba xelke tepisî ye, ya min reqisî ye. ",
"Eyba xwe bilcil dike. Eyd e, be qeyd e. ",
"Eynî jin, weynî jin, dîsa jin. Eysike ji xwe sike. ",
"Ez axa tu axa, ke golika bibe nav baxa. ",
"Ez ber te, Xwede li ser te. ",
"Ez bi dua çenebum ku, bi nifiran jî bimirim. ",
"Ez bi te, tu bi min, em tev de bi Xwede. ",
"Ez bum gur, min male, dine xwar, min çiyî te xwar? Ez çi bikim, kurke min ne  sor  e. Ez çiqasî ji belaye direvim, bela te linge min diale. (li min digere) Ez dibejim “bira“, ew ji min re dibeje “kirîv.“ Ez dibejim as ye min e, tu (ew) dibeje dora min e. ",
"Ez dibejim bibim qeymeqame Gîhadîne, ku ew nebe, gavaniye Cucane deste min maç dike. ",
"Ez dibejim ewr tune, tu dibejî we baran be. ",
"Ez dibejim ezman sayî ye, tu dibeji (we) siliye bibare. ",
"Ez dibejim hirç va ye, ew dibeje reç wa ye. ",
"Ez dibejim stewr e, tu dibejî bidose. Ez dibejim xudim im ew dibeje çend zaroyen te hene. ",
"Ez dibem bila ez dewlemend bim, ku ew nebe feqîrî (xizanî) deste min maç dike. ",
"Ez didime gula ges, ew dibe: “Bide min keleme res.“ Ez dikim li  te  dibare. Ez dixwim li te digivire. ",
"Ez diz berdidim, diz min bernade. Ez dizanim av li ser çi re diçi le bele nabejim. ",
"Ez dizanim çend revî (ruvî) di hure te de hene. ",
"Ez ez im, tu tu yi. ",
"Ez ezmana le digeriyam, li erde ket deste min. ",
"Ez hatim daweta te tu hatî diziya min. ",
"Ez hevrîska bi don im, zu ji min ter dibin. ",
"Ez ji te re, tu ji ke re? Ez ji te xilas bum, tu ji emelen xwe xilasnebî. ",
"Ez ker, te pener. ",
"Ez kevir, tu tevir. ",
"Ez kor, tu kor, ke mehîr bibe jor. Ez ku bizanibim eze kinge bimirim eze ava xwe germ bikim u kefene xwe bibirim. ",
"Ez li daweta diz im, diz li diziya peze min e. ",
"Ez li zik dixim, ew dibeje: “Wey pista min!“ Ez mer, tu mer, kî ye ji me ser? Ez mîr tu mîr, ke soqil hemîr. ",
"Ez nakim mera, kunda nakim dewsa sera. ",
"Ez namirim bi ve derbe, eze bimirim bi ve kerbe. ",
"Ez ne kewe dafika (dafen) te me. Ez neyî pirî text im. ",
"Ez pener tu ker. ",
"Ez pîvaz naxwim, ew dibeje ware sekir bixwe. ",
"Ez rim im, naçim tere. ",
"Ez singekî dikutim, tu hebinekî devejiye. ",
"Ez sirkeke dikutim, tu hespekî le giredidî. ",
"Ez tirmînî ji te re dibejim, tu yarhezokî li min vedigerînî. ",
"Ez xwe bi tehta digirim, ew jî hatiye xwe bi min digire. ",
"Ez yekî dibejim, tembura min yekî dibeje. ",
"Eze bixwim wî xwerdî, tu ye bimirî bi wî derdî. ",
"Ezî be bistan (bostan) im, le bi seqlor (seqelor)_ im. ",
"Ezîz miriye, gewrî nemiriye. Ezmane sîn ser da girt (girtiye). Ezo ne ezo, dezmala gul gevezo. ",
"Êdî çuye ber golikan. Êdî deste wî sive digire. Êdî li serî ketiye. ",
"Êdî merzel gazî dikine (ba dikine). Êdî seye wî/ we naxebite. ",
"Êl yeman, beg yeman, el rabu beg   winda bu. ",
"Êle xwe bi pîre girt, pîre xwe bi ele girt. ",
"Êseg, doseg? (qet dibe) Feqîr bi feqîran re bizewicin we parsek je çebin. ",
"Feqîr çun diziye heyv di evar da derket. ",
"Feqîr çun xwe darda bikin, le nerin ku dewlwmwnd li hewa badibin. ",
"Feqîr u jar, wek par u perar. Fermana dewe derket rovî xwe vesart. ",
"Fleh gotiye: “Aqile Kurda ye pesîn li sere tajiya min ye pasîn li sere minba.“ Ga bike ga bixwe, le tane u tolik We çi bixwin? Ga dibe cem kere. ",
"Ga dikirim dibe golik, genim diçînim dibe solik. ",
"Ga guhirande bizine, bizin jî guhurande mirîske. ",
"Ga ket, boçik li xwedî. ",
"Ga radikin, golikan li pey dixin. Ga u golik tev derdane (derdaye). Garise hur ji kefa deste wî narije. Garise xwe nede li ser warise wî. Gava kuçik beziya gur, gur mir. ",
"Gava Xwede ji yekî re lev tîne nabeje tu kure keyî? Gavan hat zeviye, jina gavan nu bezî tesiye. ",
"Gavan xeyidî nane xwe berhev nekir, hew dizanibu gundiye hevudu qir bikin. ",
"Gavan xeyidî neçu ber garane, hew dazinibu deware beste bimîne. ",
"Gaye cot e, le bele cot nake. ",
"Gaye min e, ez xuysete wî dizanim. Gaye qermo bi heft çermo. ",
"Gaye reso te çi xwariye? Tirso! (Gaye   reso kîdera te dese?) Gayek u nanek li ba wî/ we yek e. Gayek u sevek li ba wî/ we yek e. Gayîn li Muso (Gewro), cirm li Îso. Gaz jî di dest te de ye, top jî, çawa dipîvî bipîve. ",
"Geh tîr dike, geh rehn dike. Ger bi min e, ji bo min e. ",
"Ger ne fend e, ev çi dar u bend e. Geriyam li dine, xilas nebum ji mirine. ",
"Germ e, cilik serm e, sar e, cilik star e. ",
"Germ e, kel u cil serm e, sar e, kel u cil yar e. ",
"Germ germa tuyan e, kef kefa rutan e. ",
"Gesine çave xwe de nabînit, derziya çave hevale xwe de dibînit. ",
"Gewriye ru sare, te da çi çu xware, çi neçu xware. ",
"Gîha li ber gur e, gost li ber berxe ye. (mîhe ye)   Gîhistime ke “merheba“, ji xwe re tîne heft heba. ",
"Gileya bi gu ye, ne bi destan ne bi devam te vekirin. ",
"Gilî heye, gilîçî (gilîkir) tuneye. Giliya je derdixe.",
"Giliyen (gotinen) wisa dibeje ku pe pore mirov sipî dibe. ",
"Giliyen wî li ruya xistin. Giraniya xwe danî ser. ",
"Girara ser bi dew e, dixwî nexwî ew e. ",
"Girarar ku para min tev tunebe, bila serîkî sa di navda be. ",
"Gire xwe pe desten min derman neke. ",
"Gireka wî pist heçike ket. ",
"Gist bire bire ne, kure Mistefe ne. Golik e, diçe li cem gaye mezin rex dike. ",
"Golik tune bimije, xesu tune bikuje. Gorî make, golik pake. ",
"Gost hîstiye, li pey serpiyan ketiye. ",
"Gost li ser post te hur kirin. Goste berxan e, li ber çavan e. ",
"Goste berxan naxwe le pariye xwe di nav avsore datîne. ",
"Goste ciwanan dixwî tu zanî, goste pîra dixwî tu zanî dile te (ku) disewite tirsikan jî dixwî tu zanî. ",
"Goste diziye naxwe le pariye xwe di avsore dike. ",
"Goste min sor e, li xelke xwes nayem. ",
"Got ha got; got: “Çi got?“ Got: “Kere kundir kot.“ Got: “Apo jina te kevn e.“ Got: “Ji minetan çetir e.“ Got: “Apo sa tu girtî!“ Go: “Lawo apo çi se ye?“ Got: “Bavo dema zereke bu te çima nestand?“ Go: “We çaxe  yeka  me tune bu le  niha  pence  me  hene.“ Got: “Bavo eze te bifrosim.“ Got: “Lawo mirov qet bave xwe difrose?“ Got: “Bavo eze buhakî wisa bejim ku   tu kes nikaribe te bistîne.“ Got: “Bavo hirçe hek kir.“ Got: “Lawo hirç heywanek no ye, hek kir hek kir.“ Got: “Bavo min dizek girtiye!“ Got: “Lawo berde.“ Got: “Bavo ez wî berdidim, ew min bernade.“ Got: “Bira welleh min nave tu bimirî, bele min dive her daîm kodik li dest te be.“ Got: “Çave te kedirxist?“ Got: “Merive min derxist.“ Got: “Lewma wisa kur derxist.“ Got: “Daye tu çima min dihejînî?“ Got: “Lawo yeke jî daye dihejand.“ Got: “Erebo quna te res e.“ Got: “Male min ew e.“ (ev e) Got: “Ev çi ye tu diçînî?“ Got: “Kenge hesîn bu te bibînî.“ Got: “Ez ji kuçike xwe himî meraniye bum.“ Got: “Ez ku bibim dengbej, gere bi çave axa li xwe binerim.“   Got: “Ez zike te dixim, tu dibejî: Wey pista min!“ Got: “Eze sirke çebikim.“ Bu ereq (araq). ",
"Got: “Ke dinya dot?“ Got: “Ye kirî u firot.“ Got: “Ke mirî vegerandin?“ Got: “Yen ku çun serxwesiye.“ Got: “Ke mirî zivirandin?“ Got: “Yen ku dil azirandin.“ Got: “Ke rakirin mirî?“ Got: “dila pirsî.“ Got: “Keçelo te sere xwe sust?“ Got: “Min huna jî.“ Got: “Kîjan millet bas e?“ Got: “Mirove bas bas e.“ Got: “Kuçik çetir e, an beraz?“ Got: “Nelet li herduyan jî be.“ Got: “Lawo min ji te ra negot heviya Xwede bihele.“ Got: “Bavo heke heviya Xwede bima, mela we he gelekî diya min biga.“ Got: “Mal bi guyo!“ Got: “Çi bikim   kebanî ji mala te ye.“ Got: “Malo xwede bi te ra.“ Got: “Xwediye min jî.“ Got: “Mirtivo bistire!“ Got: “Tiliya min kul e.“ Got: “Pîre tu ji careke re çawayî?“ Got: “Çi zanim pes malan e.“ Got: “Te dinya çawa dît?“ Got: “Wek dile xwe.“ Got: “Tu ji çi ewqas camerî?“ Got: “Ji necameran.“ Got: “Wekî kes li pista min hebuya, te nikarîbu li min xista.“ Got: “Wekî pista min kes hebuya te nikaribu pista min bixista.“ Got: “Xwes xeber e, le min je ne bawere.“ Got: “Ziyarete min gelek caran bi te derew sond xwar, te tistek li min nekir.“ Got: “Min jî gelek caran mala te xera kir haya te pe tune?“ Gotin bas e bas, çu di curne gund de rî. (rît)   Gotin beje negot, du re bi xwe got u denge xwe nebirî. ",
"Gotin beje negot, pey da çu li ser kulîk_ got. ",
"Gotin mirîske: “Tu keliyî an kovî?“ Got: “Ez hevale xwe di sere biste de dibînim.“ Gotin pisîke guye te derman e, rî u vesart. ",
"Gotin, delalî delalî, çu di sere kaniye de rî. ",
"Gotin, here as, çu asvan kust.  Gotin: “Ave çima deng ji te te?“ Got: “Hevale min kevir e.“ Gotin: “Bave te ji birçîna mir.“ Got: “We je re sorba birinc çebikira.“ Gotin: “Bave te ji nezda mir.“ Got: “Ka hebu (ku) min nedaye?“ Gotin: “Bave te syaran kust an peya?“ Got: “Ew ku kistin, ha siwaran ha peyan.“   Gotin: “Biraye te bu axa.“ Got: “Ji min re çi jina wî bu xatun.“ Gotin: “Biraye te mirovekî çawa ye?“ Got: “Min pe re hevaltî nekiriye.“ Gotin: “Dijmin hat.“ Kor got: “Min qeratiyek dît.“ Topal got: “Em birevin.“ Ker got: “Min dengek bihîst.“ Gotin: “Gaye te dizîn!“ Got: “Wey dîke min.“ Gotin: “Çima wisa dibejî?“ Got: “Wekî min li dîke xwe bipirsiya, gaye min nediçu.“ Gotin: “Gogelisk (kelkele) cîhe te kîdere?“ Got: “Ba dizane.“ Gotin: “Gurî çima pore te tune?“ Got: “Pore xaltîka min gur e (pir e).“ Gotin: “Guro eme te bikin sivane berxan.“ Got: “Ez ji siuda xwe ne,   bawer im.“ Gotin: “Kero cehsek (dehsek) çe bu.“ Got: “Bare min li min e.“ Gotin: “Kero ji te re dehsek bu.“ Got: “Eme min kem bu, bare min zede bu.“ Gotin: “Kero kero ware em te bibin bihiste.“ Got: “Ma givzonek li wir heye?“ Gotin: “Koro te çi dive?“ Got: “Çavek jîr, parîkî don.“ Gotin: “Kul hatiye gund we ji her male du kesan bibe.“ Hemî kesî çave xulam niherî. Xulam got: “Bele yek ez le ka ye din?“ Gotin: “Kusî tu çima wisa pîsî?“ Got: “Xwede qedera min wisa nivîsî.“   Gotin: “Pisîka xalo hat te, ha pisîka xalo hat te!“ Got: “Ca berdin bila pisîka xalo be min lo!“ Gotin: “Pisîke guye te derman e.“ Pisîke rî xist xerman e. ",
"Gotin: “Piso guye te derman e.“ Firiya çu ezman e. ",
"Gotin: “Qehpe tu çima ber nagirî?“ Got: “Yek çedike yekî din xera dike.“ Gotin: “Ruto mala bar kir.“ Got: “Teysta min li piçenga min e.“ Gotin: “Terziyo (cilfe) malan bar kir.“ Got: “Derziya min li sere min ra ye.“ Gotin: “Tu ji ku yî?“ Got: “(Hela) he nezewicîme.“ Gotin; “Betalî merkuj e ha merkuj e, ha ku merek kust.“   Gotinen wî bi heft bar hingiv ve naye xwarin. ",
"Gu ji rexe re dibeje: “Delale ber dile min.“ Gu kirin nav kaxa. ",
"Gu li ruye mirov didin, neynike jî didin ber. ",
"Guh ker buye, ziman lal buye. Guh pe nake. ",
"Guhdirej ji bo ziyandayîn xwediye xwe gewerbuna xwe dixwaze. ",
"Guhe gura nîsanî hev didin. Guhe gura pe (me) nîsan dide. Guhe wî dilivin. ",
"Guhe wî hej li ser çingîniya sujine ye. ",
"Guhe wî/ we kisandin. Gula ges bî, neçilmisî. ",
"Gulan e, dew li cem hemiyan e. Gulan e, singîniya dasan e. ",
"Gulî direj e, aqil(î) qirej e. Gundek e, qilorekek e. ",
"Gundek e,  rindek  e. Gunehe xwe jî bi deyn nade. Gur bun seye qiyamete. ",
"Gur çi dizane deve buha dike. ",
"Gur got: “Hevalo, germ ne ev germ e, dema ku xwediye golikan da ser me, hevraz u berjer da ber me a we çaxe germ e.",
"Gur hata diyara, hewar kete hezara. Gur hate diyara, delil hale jara. ",
"Gur hate nav malan, wey li hale feqîr u jaran. ",
"Gur hay ji zexma xwe hebuya we dine xera bikira. ",
"Gur ji birçîbuna nikaribu reva here, digotin: “Mîratî wisa xwariye ku, nikare bin zike xwe de reva here.“ Gur u hirç bun destbira, dinya bu mehdî zeman. ",
"Gura kere Hesen xwariye, ne gazî ye (gazine) ne hewar e. ",
"Gura xwaran purt ji bimîne bas e. Guro bila tu gur biyayî, bila te golika min bixwara. ",
"Guro hijaro! Guro vexe, qijike bixwe. ",
"Guye hisk dicun dicun, li eniya mirov didin. (li pesa mirov didin) Guze xwe hesab dike, seve xelke hesab nake. ",
"Guzen puç li ser sere wî (min) diskenin.",
"Ha (wa) dikim de dimire, ha dikim bav dimire. ",
"Ha Keçel Hesen, ha Hesen Keçel. Ha kevir li cer ket, ha cer li kevir ket. ",
"Ha kulî xwar, ha Qulî xwar. Hale me ne (tu) hal e, kirina tejî serbar e. ",
"Halî wî buye hale qolo. ",
"Hasil gîha ye Mûsil. ",
"Hat ji karê, nehat ji malê. Hat ji palê, bû xwediyê malê. ",
"Hat kurê malê, nehat ziyana salê. Hat nav mala tirî, Zeyno da bêjingê li dor bênderê zivirî (fetilî) Havîna to xwar, zivistana gû xwar. Hay lê hat bazirgan e, hay lê nehat xwediyê gayê wêran e. ",
"Haya wî/ wê ji dinê tune. ",
"Hayê li min hayê, hevirmis hatiye bi livaye, xwediye livaye (kor e) dil bernaye. ",
"He di kaniya xortan da av venexwariye. ",
"Hebe Erebî ye, tune be mirtiviye. Hebe, kure kere be. ",
"Hebek kuncî ji dest narije.",
"Heca (îca) tu ne nimejkerî, pexwas bîne. ",
"Hechecke li silav hecek. ",
"Heciye bere, gula zere, heçiye pasiye   hela dehse. ",
"Heciyen me çun Letere, me got mereke je dere hat dîsa ew kere bere. ",
"Heçiye dizane, ji xwe dizane, heçiye nizane dibe qey baqe nîsikan e. ",
"Hedad_ e, nikare ji xwe re mefteke çeke pe dere xwe dade. ",
"Hedî diçim bela digeheje min, zu diçim ez digehejim belaye. ",
"Hedî diçim dibejin gej e, zu diçim dibejin bij e. ",
"Heft bave çe, illeh sîre de. Heft caran gîsine xwe le dide. ",
"Heft çîroken hirçe hene, her heft jî li ser hirmiyene. ",
"Heft hevling ro da çun, yekî dest nevete yekî. ",
"Heft hevling xistine bin nekebe gotin: “He cîh heye.“ Heft jinen esîre civiyane (rajane)   barekî hiriye, gotin: “Wey li me bekesan!“ Heftyaro, li ber çavan diyaro. Heka wî li dirane xwe xistiye. ",
"Heke berane bisko ba, we li nav peze bavo ba. ",
"Heke çemil dike. ",
"Heke ga bike ga bixwe meriye jî goste xwe bixwe. ",
"Heke ji ber sa hestiye kewan bimîne. Heke ji te re direj be, ji min re erde re dikise. ",
"Heke ne fend e, ev çi dar u bend e? Heke qun bi qune be, bila qun li cîhe xwe be. ",
"Heke Xwede got qule min yerî, ez dizanim pez ji ke re didim berî. ",
"Heke ya min/ wî bikira niha hustuna wî zer bu. ",
"Hela he kape goliktiye di stude ye. Hela he kîr li diriye neketiye. ",
"Hela he maste ser bi sîr nexwariye. ",
"Hela he rastî helikresan nehatiye. Hela he sere wî di kevire Selîme neketiye. ",
"Hema bila di eyare xwe de bixisxise. Hemi çukan hejir bixwarana, lib ji sax u hebleriyan ra nedima. ",
"Hemî fileh, ne Îso ne. ",
"Hemi riyan dizanî riya bajer nizanî. Heq hebuya , Emer Bende mehr nedikir. ",
"Heqe Elî dixwaze ji Welî. Heqe xwe jî dide, sere xwe jî diskene. ",
"Heqiye di deste neheqiye de bare-bar e. ",
"Her pexemberî bere dua li xwe kiriye. ",
"Herana ritlek genim re çi sîs, çi tevere? Herdu jî ruye hevdu dison. Herdu jî tuyî deve hev nakin. Here ser kaniye, kaniye (le) zuha   bibe. ",
"Hereket kor e, ziman zor e. (sor e) Herke yekî got: “Mala min ya te ye.“ Ma te agir berdeyî? Herne kure, li min mikure. Hesike ji negre re got: “Nava te teniye, negre got: “Tu di nava min de diçî u teyî?“ Hesin bi sarî dicu. ",
"Hesinekî bavejin ber linge wî/ we. Hesp bi hevsaran, mer bi qiraran. Hesp ji dest çuye, li pey hefsar ketiye. ",
"Hesp li ser çar lingan re diçe, le dîsa jî lingen we disimite dikeve. ",
"Hesp tune afir çedike. Hesp tune hefsar digere. Hesp tune zîn dikire. ",
"Hesp u kesp li nik (ba) wî yek in. Hesp ya min e, ez xuysete we   dizanim. ",
"Hespa min sîwar be le, piste neesîne. ",
"Hespa min siwar be quna xwe te de danegire. ",
"Hespe çi pelikda te xane. Hestî kere hilnagire. ",
"Hestiye ziman tune,  digere. Heta (ku) ew be hestire (jî) bize.",
"Heta (ku) male me hebu alem doste me bu, male me xelaz bu, Heta ani serî, heft kiras qetand. Heta boçikeke peve girenede nasekine. ",
"Heta buk fetilî, dewet betilî. Heta buk xemilî (dawet) govend betilî. ",
"Heta çavek derman kir, yek jî kor kir. ",
"Heta genim firîk e, mele sirîk e. Heta hebu dimis, ez mam u tu pis;   dema ku nema dimis, ez Motî u tu Bohtî. ",
"Heta hebu sillik-millik, dema nema keder kulik. ",
"Heta kirase wî/ we bisewite, cane min we bisewite. ",
"Heta ku dîk mîr u tajî kizîr be, tu mevanan li dere male nabînî. ",
"Heta malek ava kir, sahrek weran kir. ",
"Heta min xwe nas kir, mal jî li xwe xilas kir. ",
"Heta mirine çav li kirine. Heta mirine li ser kirine. ",
"Heta nebeje tireq nabeje heq (sedeq). Heta neçe diyare gore, mirin nakeve bîre. ",
"Heta qeliya me hebu, Mamik buka me bu; roja qeliya me xilas bu, Mamik çirtek da xwe ji me derbas bu. ",
"Heta xanim xemilî, govend fetilî. Hetanî min xwe nas kir, emire xwe jî xilas kir. ",
"Hevaltî, bi rastî. ",
"Hevraz tu dikim simbel e, berjer tu dikim rih e. ",
"Hey dest e, hey zozan e, esil xwedan e. ",
"Hey desta Muse u hey dare derguse. Heye terk, nîne berk. ",
"Heyf li cane çuyî. ",
"Heyfa ciwaniye pîrî li pey e. Heyrana kuçike gurex, li beriye diewte, li zozane gur miye berdide. ",
"Hijdehe bihare nagire ji bihare heya bîst u çare. ",
"Hijdeye adare nagire ji bihare dur nîne du bohisted befire bene xware. ",
"Hijdeye adare, melkejat hate xware peva kir gîhaye bihare. ",
"Hilkisiya pere esmana. Him çilike, him silike. ",
"Him digirî, him dikene. Him dinale, him vedimale. ",
"Him ji dere, him ji mizgefte bu. Him ji kare bu, him ji yare  bu. Him ji kere bu, him ji Pere  bu. Him ji kirike bu, him ji belike bu. Him ker e, him se ye. ",
"Him riya Xwede, him ya însanetiye je stendiye. ",
"Him sere xwe diskene, him jî besa xwe dide. ",
"Him sil e, him kul e. ",
"Him tîr dike him rehn dike. Hîn deve te germ e, deng bike. Hin dikin hin jî dixwin. ",
"Hin hingiv dixwin u mes bi hinekan vedidin. ",
"Hin mirine, hin jî tevakirine. Hinceta kulîlka, çune sulika. Hindik re jî, gelekî re jî nabeje sukur. ",
"Hindik rindik (bila hindik, bila rindik).",
"Hingî min kir u got, çerme sa ma firot, Usman u Qemrî min nekir cot. ",
"Hingive debeyî, di eyare kuçik da ye. Hirç hat va rez, diz hat va pez. ",
"Hirç u govend, rovî u suk kevrojk u dewlok. ",
"Hirçe heta xwe de nedît bawer nekir. Hirçek ji rezekî xeyîdiye, ritlek dimis zede buye. ",
"Hîv hîv e, eyb li we jî heye. Hok e, rok e. ",
"Holî got Golî: “Heke em milen xwe nedin ber Solî, kulke me nabe ulî.",
"Hoste neçar rabe rune weke hercar. Xwede yeke dergeh hezar. ",
"Huke dike muke. ",
"Hur bajo, zu bajo, dur (kur) bajo le ga neesîne. ",
"Hure tendur (tenur) dada, qehpe pe veda. ",
"Hurik hurik dagirt turik. Hustiye xwe li ber direj kir. ",
"Îro doro te ye sibe dora min e. Îro jî mast sibe jî mast Îro roja te ye, sibe roja min e. Îsal dîsa bal kesiv e. ",
"Je direvim pe digerim. (Je revim, pe gerim) Je erzan xilas bu. Je ket, pe ket. ",
"Je re kap naye avetin. Je re sîr qelandiye. ",
"Je xwîn vedirese. ",
"Jev direvin, roja reve tev direvin. Jî ave re gotin: “Çima guse gus dikî?“ Got: “Hevale min kevir e.“ Ji axe pirttir tune ye, mar bi qinyat dixwe. ",
"Ji barane revîm, kete ber zîpike. ",
"Ji barane revîm, li teyroke qelibîm. Ji behre xilas bu, di çem de xeniqî.  Ji ber barane çu ber zîpike (teyroke). Ji ber dilope çu ber merzibe._ Ji ber serî neçu heya sibe. ",
"Ji beriya emre xwe xeber dide. Ji beriye te ji min sîr dixwaze. ",
"Ji betalî bi sere kîre xwe re dilîze. ",
"Ji betalî kera bave xwe da ber dasan (ber keran).",
"Ji bine sola xwe re beje. Ji bitrî hatiye beran. ",
"Ji bo çile dixwe kule. ",
"Ji bo çile xwe dike (kiriye) gile. ",
"Ji bo gurzek gîha, lodeke disewitîne. Ji bo keçeke lihefeke disewitîne. ",
"Ji bo miriyen xelke me pore xwe veru, miriyen me mirin me dest avete (ku) pore me nemaye. ",
"Ji bo nanekî avranekî (arvanekî) xera dike. ",
"Ji bo nefse, xwe daveje hepse. Ji bo xatire xatiran çu ser dine gawiran. ",
"Ji bo xatire xatiran, da bare qantiran. ",
"Ji bo xatire xweyî, mirov kevir naveje seyî. ",
"Ji çav ketiye. Ji çav reviye. ",
"Ji çaven xwe bawer nekir. Ji çîze derxist (derbas kir). Ji delava ketin çirava. ",
"Ji derdan rih berdan. ",
"Ji dest derketiye (reviye). Ji dest derketiye naye. ",
"Ji dest ketiye. ",
"Ji dest pesîra xwe dadisîne. Ji dest tistek naye. ",
"Ji dev gerandin ket. ",
"Ji deve ketiye hop hop je te.  Ji deve re gotin: “xet“; got: “Ez nikarim qet.“ Ji deve re gotin: “Ye (we) te bisînin dawete.“ Deve got: “Ev sutiye minî xwar ne layiqî daweta ye; yan we min bibin mese daran an ji bisînin Rewane birinc.“ Ji deve re sol dikirin, jojî got pepe min jî. ",
"Ji deve wî/ we girt. Ji deve xwe revand. ",
"Ji dijminan re zare serîn, pista hisk. Ji dil re derbas dibe...",
"Ji dil xwîn dilop dike. ",
"Ji dur ve, di keça mîr ve. ",
"Ji erde heta esmîn neheq e. Ji ers u kurs xeberdide. ",
"Ji es be serî ar be je bawer neke. ",
"Ji esîran esîra me, ji gundan gunde me, ji malan mala me, ji mala me jî ez u birayen xwe, le zede zede jî ez. ",
"Ji evda re dost u yar e, ji min ra gure har e. ",
"Ji feleke re dikeve dewe. Ji feleke re xeberdide. ",
"Ji golike re gotin: “Eme boçika te je bikin ji kesîre nebeje.“ Golike got: “Ma ez nebejim we nebejin ka boçika te.“ Ji gur birçîtir, ji mar tazîtir e. ",
"Ji gur re gotin: “Çima stuye te stur e?“ Got: “Ez bi deste xwe dikim, bi deve xwe dixwim.“   Ji gur u delegure re tu re nema. Ji hal ket. ",
"Ji hebek tirî meserekî çedike. Ji hekeke çedike qeyxaneke. (qeyxaneke çedike) Ji hekîman re dive (dibe) du fincan yek kase xiraban, yek kase qencan. ",
"Ji helîne çu kulîne. ",
"Ji hersan ezmana ket. ",
"Ji hespe peya bu, li kere swar bu.  Ji hestire re dibejin çoke te xwarin, dibeje qedera min rast e. ",
"Ji hevdu re hevrîske ave çedikin. ",
"Ji hevdu re mer in, ji xelke re ber in. ji hinekan re besbirlik e, ji hinekan re seferberlig e. ",
"Ji îne heya îne, çekir cila meîne, ew jî kin e, nagiheje ser qune. ",
"Ji jinan ji dotmam, ji suran sure Sam. ",
"Ji kaliye jî pîriye, mirin çetir e ji feqîriye. ",
"Ji kare jî, ji yare jî bu. ",
"Ji ke re dibejim “brawo“, ji min re dibeje “bira xwaro.“ Ji kefa mehuja (mewuja) dil çu guhuja._ Ji kerbana xwîn le miçiqî. ",
"Ji kere waye ku manker horî ye. ",
"Ji kevire as girantir tune, bi mixekî radibe. ",
"Ji kewjale re gotin: “Tu çima xwar re ve diçî?“ Got: “Keysa min hew je te.“ Ji kirase cane xwe re ser e. ",
"Ji kirinen sex u melan, dîsa rehmet li cahilan. ",
"Ji kîse kirim, xwes dibirim. ",
"Ji kul u derda, ru u simbel berda. Ji mejburî mirov goste kewan jî dixwe. ",
"Ji mela bangdan. ",
"Ji meran mere pesîn, ji hacetan simtiras. ",
"Ji mewujekî kergekî dikelîne. Ji milka as, ji sineta simtiras. ",
"Ji milkan as, ji jinan jinen sas, ji meran meren ne bide pes, ne bide pas. ",
"Ji min ketiye, pesiya min dihere (diçe). ",
"Ji min re bike, ji xwe re bibe. ",
"Ji mîrate re gotin: “Tu diçî kîdere?“ Got: “Cîhe ku bikaribim bixim mîrate.“ Ji nan u ave qut bu. ",
"Ji paniye xwîn nehatiye ku dil bisewite. ",
"Ji perxanen wî/ we girtiye. Ji peze pir, ma kavira kur. ",
"Ji piran pir, ji hindikan hindik. Ji qatutya (xeleya, tune buna) meran, nave dîkan danîn Evdirehman. ",
"Ji qehra xwe daveje behra. ",
"Ji qireja wî/ we mar vedirese. ",
"Ji qurane kirasek xwe kir dîsa ji kesî je bawer nekir. ",
"Ji re derketiye. ",
"Ji rovî fenaktir tune, ji eyare wî pîstir tune. ",
"Ji ruye wî jehr dibare. ",
"Ji sed cîhî birîndar im, edî nikarim bejim sax im. ",
"Ji sere hefte heft bave te mezintir e. Ji sere xwe zedetir xeberdide. ",
"Ji serma (na) heken hesinî dike. Ji sîr tirsiya, pifî dew kir. ",
"Ji te hereket, ji xwede bereket. ",
"Ji tirsa kuçikan newere here gund dibe: “Sev res e.“ Ji tirsa zirav le qetiya. ",
"Ji tivinge re nîsan, ji hespe re meydan. ",
"Ji tunebuna seran, rovî xwe nîsan dikin wek meran. ",
"Ji weliya perî, ji periya xwelî. ",
"Ji weyne jinan çiyaye Cudî xwar buye. ",
"Ji xelke re cîh u war e, ji min re erde sar e. ",
"Ji xelke re edet e, ji min re qebhet e. Ji xelke re jîr e, ji xwe re kor e. ",
"Ji xezale bezatir tune, ew jî rizqe xwe dixwe. ",
"Jin biriye, he qelen nebiriye. ",
"Jin çav li der e, mer xwelî li ser e. Jin çun hewara, mer ketin kewara. Jin derkete ser serî, de avete ber derî. ",
"Jin hene wek mirîska kor in. Jin heye zeviya li ber gund e. ",
"Jin jî hene, jan jî hene, melhema dilan jî hene. ",
"Jin jî henin, jinkok jî henin. Jin jin gotî mer mer gotî. ",
"Jin u mer ser kirin, kemaqilan je bawer kirin. ",
"Jin u mer, tevir u ber. ",
"Jina an mal u mer, an tevir u ber. ",
"Jina bira weke gura. ",
"Jina diya du dotan, dide xwe du lotan ne li vir ne li Cizîra Botan. ",
"Jina kofî u kitan. ",
"Jina mere çe ye, dine je re de ye. Jina mere xerabe, him diz e, him qaw e. ",
"Jina xelke ramusanek, hespa xelke meydanek. ",
"Jinbave jina bave, birçîme ber dolabe. ",
"Jine dil kir dîwar qul kir. Jine dil kir mere xwe sil kir. ",
"Jine ruhike, daye huhuke (buxuke). Jinike got mela: “Mehra min mehkem nebire, ez (yeka) destpe nesekinîme.“ Jiyanek nemir nejî dijî. ",
"Jojî deste xwe çeliken xwe dide u dibeje: “pore wan çi nerm e.“ Jujî tejiken xwe tîmar dikir u digot: “Ez qurbana purta we ya hevrisim bim.“ Ka (kaya) kevn u teze dide ba. (Be) Ka bare wî ceh e an genim e? Ka çu, ma dan. ",
"Ka ne ya te ye, ma kadîn jî ne ya te ye? Kal e, le gale-gal e. Kala dide piçenge. ",
"Kalbune li min kar kir, xortaniye mala xwe li cem min bar kir, qîza ruye xwe ji min guherî, buka dile xwe ji min sar kir. ",
"Kale benefsî, pîre bekesî herduyan li hev pirsî. ",
"Kalo ji min dur here, fiskîniya poze te te. ",
"Kana aqil e. ",
"Kaniya dilan, ciwata cahilan. Kape wî mîr hatiye. ",
"Kar ket bertila, gu ket (agir ket) rewsa feqîra. ",
"Kara te ji min ra, kerema Xwede ji te ra. ",
"Kare min bi xelkano, cane min bi heseno,_ male min bi talano. ",
"Kare ne ji min ra, baye wî di sere min ra. ",
"Kare xwe bi xelke kir, bi nave xwe kir. ",
"Karoz-karoz, dîsa kere boz. Kasa xwe kasa dikisînim, ji mamanan (hevalan) namînim. ",
"Kaxeza gur e, ne kes dixwîne, ne kes guhe xwe dide. ",
"Kaye u dan tev li hev dike. Ke buk e ew pe ra berbu ye. ",
"Ke çav sere min dikeve (sere min   dibîne) sere xwe bi heft rengan giredide. ",
"Ke dinya xwar? Ye di ber ehmaqan de xwar. ",
"Ke dîtiye kale bi guhar, pîra ling xirzal, zivistana du bihar? Ke gotiye dewe min tirs e? Ke gotiye dizo malî ava? Ke kare pir kir, keziya xwe kur kir. Ke kir xatun? Mer kir xatun, ke kir darqun? Mer kir darqun. ",
"Ke nane min xwar, (ewî) tirba min kola. ",
"Ke nîre hevaltiye xwar kir, stuye hevale xwe kul kur. ",
"Ke seh kiriye, ke xwendiye? Ke tir kir? Xerîbe gund kir. ",
"Ke tir kir? Yen be de u be bav. ",
"Ke vegerandin mirî? Yen ku dil kirî. Kebanî bun sise, kodik li ber se. ",
"Kebaniya jehatî bila nîve qeliye jî bixwe. ",
"Keç u kuren male, gula de u bave. Keça gan nîsan-daye didan. ",
"Keçe ha keçe çi di keçe de ma. Keçe ha keçe çike min di keçe de ma. ",
"Keçelo mu bi sere te nîne, got: “Keziyen xaltiya min li qune dikevin.“ Keçelo nave min nave te, kume min sere te. ",
"Keçik çune halhala_ zik tijî, turik vala. ",
"Keçika be bav, çiyaye be av. Keçika be de wek çiyaye be re. ",
"Keçika li ser kere berî xwe tuyî min kir. ",
"Ked kiro, keda xwe nexwaro. ",
"Kefa me bi xunave xwes bu, xunave jî kurek mirî anî. ",
"Kefene xwe çirand (dirand). Keftaro, li ber çavan diyaro. Kelhî ne, bes tistek li mala wan   nîne. ",
"Kelk li ser kurke xistiye. ",
"Kelka xwe, selka tu je xilas nakî, ne sax im, çar liv tu jî texe te de. ",
"Kelkelo cîhe te li ku ye? Got: “Ba dizane.“ Ken dike, fen dike. Kene be ariye pe girtiye. Kene miriyan pe te. ",
"Ker bi hestî nakeve. ",
"Ker çi dizane zeferan çi ye. Ker deve wî venake. ",
"Ker dikeve, dibeje: “Hella Xwede!“ Ker heft avjenî dizane, tere ber ave hemiyan ji bîhr dike. ",
"Ker ker e di cîhkî de dikeve heriye heft salan li wir ra naçe. ",
"Ker ker e, di pira qul re derbas nabe. ",
"Ker u gej guhe wî tijî qirej. Ker u kurî li hev zirî. ",
"Ker u mekteb?   Ker ve best, xem verest. ",
"Kera ku bare min ne lebe ez nabejim “ços.“ Kera min dimire boçika wî dixwure. Kera xwe di berika wî de dîtiye. ",
"Kerambere ber baye mikur te. Kere di kurtan de rî. ",
"Kere got: “Bar min nakuje, serbar min dikuje.“ Kere guhe berxe girt, (dîsa) kere kir zirîn (qarîn). ",
"Kere lawe kere, av li bere, bikeve sere, heb ji hebe bike dere. ",
"Kere nabe ber ge, ge tîne ber kere. Kere pir bez, bu xware guran. ",
"Kere res, li ber danîn qasle zebes, got: “Min dive welate xwes.“ Kergu dibeze u tajî dibeze, her du jî dibejin: “Ya Xwede!“ Kergu ji çiye xeyidiye, çiya haj pe tune. ",
"Kerguska xaman e, dev diçere, çav li   banzdan e. ",
"Kerguske got: “Min da hevraza, tira min bidin cambaza; min da berjera, goste min bidin ber kera.",
"Kerî berdaye li pey qerus ketiye. Kerî bi kerîtî daye, pey da qerus qeruse. ",
"Kero ji te ra dibejim, mevano tu guhdar be. ",
"Kero nemire bihar hat, pîre nemire pincar hat. ",
"Kero, mevane hero. Kero, weke hero. ",
"Kes je re (nikare) kirasa biqetîne. Kes li bave min napirse, herkes li diya min dipirse. ",
"Kes nikare je re solan biqetîne. Kese mino, deste mino. ",
"Kesî negotiye ev mala dizan u xumarbazan e. ",
"Kesib dibeje: “Heya sibe bi Xwede ra   me.“ Kesibe (xizane) be nesîbe. Kesibe asan e rojen siliya dest u piye wan zuhan e. ",
"Keso keso carek beso. Kesîs hero kata naxwe. Kesîs hîmî kata buye. ",
"Kesk e, ruye kebaniye res ke. (Xwes ke) Ket nav dev u diranan. ",
"Ket xeberdan, ker da guran. Ketiye ber destan. ",
"Ketiye binî. ",
"Ketiye daweta cuna. Ketiye rex. (Dikeve rex) Ketiye zike diya xwe. ",
"Kevçiyan nexe (naxe) gurz. Kevçiye çila, nu got: “Bismillah!“ Kevir ber piye te bibe pener. ",
"Kevir cer ket wey hale cer, cer li kevir ket wey hale cer; wisa an wisa wey li hale cer. ",
"Kevir daye ber dile xwe. ",
"Kevir li kewe neket, kew li kevir ket. Kevir u kuçik li min barî, xer u xwesî li te barî. ",
"Keviran giredidin u kuçikan ji berdidin. ",
"Kevire pesa xwe hursand. Kevire seriyan e. ",
"Kevire takese ye, kîjan ceme bar xwar bibe xwe dide wî alî. ",
"Kevire xorza ye. ",
"Kevirekî hilke, (we) pirsa xwe binke. Kew firî, qismet birî. ",
"Kew li kundir ket, ne kundir li kewe ket. ",
"Kewaniye çelek dot. Çeleke sîre xwe ret. Got: “Dile patise ji me xera buye.“ Kewen lisandinî, wek kelandinî. Kewkiye pasîn li tesikan e (gehan e). Keysa te ku hat, fersend u xebat. ",
"Kî dike kî dixwe?   Kî dixwe kî li xwe dixe? Kî diya min mehr bike, ew bave min e. ",
"Kîder tav be kurke xwe li wir radixe. Kîder xwar e, ew der ji min re war e. Kîdere komek, we dere kedek. ",
"Kilek run li ser dile xwe da. Kinca hevalan ro danek, hespa hevalan meydanek. ",
"Kir nekir tu re te re nedît (dernexist). ",
"Kirase be pasuk (pastî) dixe hurtiye mirov (di hustiye miroav de datîne).",
"Kirase kires e, qusase quses e. Kitik ne li mal e, nave misk Evdirehman e. ",
"Kone resî dev jev e, ne nan e, ne av e. ",
"Kor gote kor: “Min çave teyî kor çikiro.“ Korbe jî, kulbe jî cixarekesekî   tejmeul e. ",
"Koro tu li min binere çavekî, ez li te binerim herdu (du) çavan. ",
"Ku be çenge min te bibînî renge min. ",
"Ku bexte etîman hebuya, bave wan zu nedimir. ",
"Ku çingiya tas, ha vir, ha rast. Kuçik çi dizane çarix çiye. ",
"Kuçik hestiyan dixwe haj quna xwe dike. ",
"Kuçîk, kuçik e. ",
"Kuçike me ye, li ber dere xelke direye. ",
"Kul u kor li hev civiyan (vehewiyan) li dikana Evdilor. ",
"Kula dilan e, xeftane milan e. Kula Mendo, kulor in.",
"Kulav guyo malî ava. ",
"Kulinge wî serî care li cîhkî dikeve. Kum avetin, ser xwestin. ",
"Kuma daynîn pirsa je bikin. ",
"Kume Belo li sere Celo (ye) ye Celo li sere Belo. ",
"Kume min ji rastiye qetiya ye. Kume Xiço li sere Piço, ne hat ne diço. ",
"Kume xwe bi xweliye ve daye sere xwe. ",
"Kume xwe daye tel. Kume xwe xwar kiriye. ",
"Kund dibeje ez ew qas im le aqile min jî ew qas e. ",
"Kura zer bu, kura der bu? Kure mino ne ji mino, roja koçe bare mino. ",
"Kurek heye gula bave, kurek heye kula bave. ",
"Kurk ketiye mejiye wî. ",
"Kurm di sere wî de dilive (dilivin). Kurm ketiye dile wî. ",
"Kurmance nezan got: “Bila bibe erzan,heta ku dev u deling le bune pizdan.“   Kurmancî ter e, xew je re xer e (xew je re çi ye?).",
"Kurme sîrî heya pîrî. ",
"Kurtikî çuxe dew tune bixwe. Kusî heken xwe dixe bin axe u dibeje: “Heke ji Xwede re dive we çelika derxe.“ Kusiyan ji delava xezale av venexwarin. ",
"Kustiye di ber xelke de ye. Kutilka min jî ji Berfo ye. ",
"Lawe Mence çu qezence. Lawike Engorî, nabe memure Stembolî. ",
"Lawike Qureysî, kes nîne pis neesî, bele xîret namuse dikesî. ",
"Lawo li her dere ji xwe re maleke   çeke. ",
"Le dev xwar kirin (dike) Lehat bas hat, lenehat je nehat. Lehat bazirgan e, le nehat xwediye gaye weran e. ",
"Lelîxan e, xwediye kired giran e. Leskere Rome ye, nan li ser çoke ye. Lev li erde re dikise. ",
"Leva xwe le xwar dike. ",
"Levek erde ye, yek li esmîn e. Lexistina koremarî, ne dîtana deyndarî. ",
"Li alîkî sahî ye, alîkî sîn e. ",
"Li bejne neherî bi zeran kirî, laçik vekir sere gurî. ",
"Li ber çava buye mare res. Li ber defa bedeng dilîze. ",
"Li ber defa cuna direqise. Li ber ruya buye perde. ",
"Li ber tira wî dilîzin. ",
"Li Bexdaye xurme zef in ji min ra çi ye? Li ceheneme sîran dikutin, tu   kilaman dibejî. ",
"Li ceheneme sîran dikutin, tu kulora dipejî. ",
"Li deve wî/we dinere. ",
"Li dîna temasekin an sahiya an sîna. ",
"Li dur geriya, li nezik dît. ",
"Li ezmanan geriya, li erde dît. Li gorî make, golik pake. ",
"Li kere mirî digere (ku) nela je bike. Li kere siwar buye, li kere digere. ",
"Li koriye li kaliye, mirin çetir e ji feqîriye. ",
"Li mexel piskul tune, li pireze deve tune. ",
"Li mine li mine çi bikim dernakeve li ber hukme jine. ",
"Li mine li mine, rovî naçe kune. Li ser boçike hesin dibe. ",
"Li ser çavan re birî hene. ",
"Li ser çi de mîz bike we zuha bibe. Li ser dîware alebile sekiniye. ",
"Li ser riya Helebe nale kera dipirse. ",
"Li ser tiliya mirov de mîz nake. Li ser tiliya xwe ve dide lîstin. ",
"Li vir teq, li wir teq, heta çune dinya heq. ",
"Ling kiriye soleka teng. Ling le hilda ye. ",
"Linge qijike sikenand. ",
"Linge rovî girt avet nav holîtka mirîskan. ",
"Linge dîk di nav tase de tîtiye. Linge gur girtin avetin nav koza berxan. ",
"Linge wî di nav zike wî de ye. Linge wî erd girt. ",
"Lingek li ve dine ye, lingek li we dine ye. ",
"Lîstina pisîke ye, mirina miske ye. Lolo lolo ji min re ji lolo. ",
"Lomekaro, gunehkaro.",
"Ma (çima) hespe tu revandiyî? Ma (tu) herfa qurane ye? Ma alîkî cendek helal yek heram e? Ma dar tehl e, bere dare sirîn e? Ma dermala sor me sandibu pey. Ma ev guye henakan e? Ma eze herim ser gulen sor? Ma ga dike, ga dixwe? Ma gotina te kerta kevire? Ma min ev ruye xwe di as de sipî kiriye? Ma paniya diya min pe xwîn buye? Ma peze meyî tev hev em nikarin veqetînin? Ma qasa kembera te sikest? Ma te deste xwe bîhn kiriye? Ma te deve nedît reze, te piskul jî nedît li feze? Ma te kapek xwariye. Ma te navika wî birî ye?   Ma te riya xwe sas kiriye. ",
"Ma tu ji pere esmanan hatiyî? Mal (malxetî) ket deste kurî, risqe sale se car birî. ",
"Mal birçî ye, kebanî li ber çi ye? Mal çune zozana, xwelî li ser qun pena. ",
"Mal ji miskan ru res e. ",
"Mal mala te ye, le ber ve firaqan neçe. ",
"Mal sewitî le ji miskan ra jî nema. Mal ter e, kebanî ser e. ",
"Mal u mevdan, nebu qutik u fîstan. Mal xizan e, kebanî nezan e. ",
"Mala bava zeynet in, ava cere wan serbet in, dayik ku dimirin, zeyî ten li ba jinbira be rumet in.",
"Mala bave buke gavan e, qelende buke giran e. ",
"Mala buke def u zirne, mala zave haj tu tistî tune. ",
"Mala gavan e, naze (dilika) zeriye giran e. ",
"Mala hebune mala kereme, mala tunebune mala kure kere. ",
"Mala kura, mala dura. ",
"Mala li ser mala, yek xirab, yek ava. Mala me çoye me ye, çoye me li ser mile me ye. ",
"Mala pîre, gora pîre. ",
"Mala pirmezin xerabu ji bin. ",
"Mala Seref bi xwe hindik bun, ew jî hin kuro, hin silo, hin seqet bun. ",
"Mala virekan xirabuye, kesî je bawer nekiriye. ",
"Mala wî bare dîk e. (dîkekî ye) Mala wî li ser pista wî ye. ",
"Mala xelke disewitî, ewî jî li ber firike xwe diqeland. ",
"Mala xwe daye ser pista pisîke. Mala xwe li pisîke bar kiriye Male axe diçe, cane xulam diçe. Male da hesti sikandiye. ",
"Male li malxe dipe. ",
"Male malyemeza, xware tarîx bilmeza. ",
"Male qun dive, girare run dive. Male tune evranok, nave jinike dîndarok. ",
"Male xwe di ave de berdaye. Malek e, danzdeh rispiyen wan hene. ",
"Malxe me Silo be, we xwarina me çilo be. ",
"Mam Hemdan, me çel u gul li der dan, mane em u xeberdan. ",
"Mange dosîn u qezwan_ frostin. Mar dibeje: “Min dikujî (bi) dijminatî, min çal bike (bi) dostî.“ Mar ji punge xolî dibu (direvî), pung li ber deve qula mar de hesîn bu. ",
"Mar mar e, dema ku mirov ave vedixwe li mirov venade (naxe). ",
"Mar pak buya, linge wî nediketin zike wî. ",
"Mast, sed carî mast. ",
"Me buk anî lez u bez, me leda (daye) rez u bez; sivika male dîsa ez. ",
"Me Cizir ava kir, Heso ser de zava kir. ",
"Me di xewna sevan de jî hevudu nedîtiye. ",
"Me got em herin mala ape xwe firo firkin; me negot eme herin guliya kurkin. ",
"Meha adare av firî sere dare, bizin kalî ser kare, nîsanen bihare. ",
"Mehna lorika_ dixwe klorika._ Mehna sele, gerî nav ele. ",
"Mehna sergîna çu gunde Mexîna._ Meîna pîr, hefsare rengîn? Mejî le buye av. ",
"Mela jî di qurane de sas dibe. ",
"Mela nivist çekir ji bo qîze, gu hat li tev mîze. ",
"Mela xwarin dît quran ji bîr kir. Mele mele ber kendal. ",
"Melevane ku xeniqî. ",
"Melezade mele-zade, me ter xwar zed u zewad e, îcar her yek me di alîkî de bade. ",
"Mer bi muye xwe, jin bi ruye xwe. Mer çav li der e, jinik xwelî li ser e. Mer henin wek dewara res in, dema ku zike wan ter dibe, an merekî dikujin an jineke tînin. ",
"Mer kustin nerme-nerm, qîz xwestin germe-germ. ",
"Mer mera nas dike, qus paldime kere nas dike. ",
"Mer mera nas kir, quse quze kere nas kir. ",
"Mer tu (ne) guhar u ben in ku tu guhe xwe de kî. ",
"Mera mer dikust, Fata Kore (ber   derî) hurpizur disust. ",
"Mera xwe avetin kewara, jin çune (sandin) hewara. ",
"Merde ji kîsmale xelke ye. Merde ne bi male xwe ye. ",
"Merik ket bin siya axe, axe ket bin siya doxîna xwe. ",
"Merik na pîre, pey ra guneh hat bîre. ",
"Merim kure mera me, îro jî mast sibe jî mast. ",
"Meriv kevira daveje birca belek, naveje sepeta rexe. ",
"Merive be guman, be dîn u be îman. Merivekî nexeritandiye. ",
"Merivekî pist rast e. Mertale wî ruye wî ye. ",
"Mevan got: “Hewa çawa ye?“ Xwediye male got: “Riya rewiyan vekirî ye.“ Mevane yekî, mevane gundekî. Mevano te xwarine bixwî?   Mevano tu terî an birçî yî?  Mewluda xer u beser, heçiye dewlemendin bikisin ber diya feqîra bigen bavejin (derxînin) der. ",
"Mezera de li ber qîze. Mezhebe wî fireh e. ",
"Mezin kir bi nane xwe, kir agir berda cane xwe. ",
"Mî bi piye xwe, bizin bi piye xwe. Mî birî, sîr firî. ",
"Mî bun kavir, kavir jî bun vir. Mî dikale, berx li mal e. ",
"Min bizanibiya (ku) bave min we bimire, mine guhe wî tijî genim bida. ",
"Min çi xer dît ji bendere, çi bibînim ji kozere. ",
"Min çikir ji peze pir, eze çi bikim ji kavira kur? Min daye bi tetika, pey digerim bi pepika. ",
"Min feraseta xwe ji be ferasetan girt. ",
"Min ji ke re got: “Bira“ ji min re got in “birakuj“. ",
"Min kir, te kir, Sezere nave xwe kir. Min nan ne bi guhe xwe ve, bi deve xwe ve xwariye. ",
"Min xelk hîn kir lîstike, du re kesî deste min negirt. ",
"Min xwedî kir bi bistane xwe, jine ji min stend bi navrana xwe. ",
"Mîna dupiska boçika xwe daye ser milî xwe. ",
"Mîna gura gost dixwe, mîna melekan xofe dikisîne. ",
"Mîna gure yekane. ",
"Mîna kersege di hale kevir de bigirî. Mîna kewe teqle. ",
"Mîna masiye ku av li ser be birîn. Mîr dimire evdal dijît (dimîne). ",
"Mir kere qazî, her kes çu tazî, qazî bi xwe mir, kesî le pirs nekir. ",
"Miraze be dil, wek kirase be mil. Mîre miska, buye axaye giska. ",
"Mirî ber bi qebre dibirin, teme mirî ber ve male bu. ",
"Mirî henin ku hewceyî sîne ne. ",
"Mirî hew dizanin, zindî her roj hewle dixwin. ",
"Mirin heq,  gor  ferz. Mirin je re buye zere zer. ",
"Mirin mirin e, le ev çi kirin e? Mirin mirin e, le xire-xir çi k... min e? Mirîsk mirîsk e, ave vedixwe li ser xwe re xwede dinere. ",
"Mirîsk nikule xwe ave de dike bere xwe bervi xwede dike. ",
"Mirîsk res e, hek spî ye. ",
"Mirîska me ye, diçe kadîna xelke de hek dike. ",
"Mirîska res e, her roj nexwas e. Mirîske çav da bete, buhistek ji qune kisiya. ",
"Mirîske çav da qaze ket heka xwe sikand. ",
"Mirîske hek kir, heval ji xwe re   çekir. ",
"Mirîske min tunenin, dora mala min zîrç e. ",
"Miriye par havîne, nu hatiye sîne. Mîro borî. ",
"Mirov sivra ku ser nan dixwe, kere le naxe. ",
"Mirov zine dike, le ne bi de u xweha xwe re. ",
"Mirtibe zir e, ne li defe ye, ne li zirne ye. ",
"Misk li dikana wî bigere, boçika wî we be xuyan. ",
"Miskan gincî dike. ",
"Miske kor hingî axe dikole, li ser sere xwe de dike. ",
"Miskek dikeve sîtila sîr, ew sîr te rijandin. ",
"Mu ketiye sîtila dew. ",
"Mus xwes Mus e, piste Algus e. ",
"Nabeje kafirim an (jî) misliman im. Nabeje ke kir, debeje ke got? Naçim cineta bi minet. ",
"Nagejime te xwe ji te dibuhirînim. Namirim tîra pera, dimirim xebera we ra. ",
"Nan bi xwe, xwe bi tam. ",
"Nan da ber me, ço da ser me. ",
"Nan da ber me, tajiya xwe berda ser me (da ser me).",
"Nan genimiyan neke. ",
"Nan padisah gost wezîr, ye din kizîr- mizîr. ",
"Nan pir, pîva pir, gelo eva çima mir? Nan u dew e, taqet eve. ",
"Nan u dew, xwarina derew. Nan u mast, xwarina rast. ",
"Nan u sîr, xwarina jîr. Nan u tajî, xwarina tazî. ",
"Nan u xwe ya wî/ we li ser çoke ye. Nan xwera caw dir. ",
"Nane be xweye dixwe, tiren sor dike. Nane cehîn dixwe, tire polayî dike. ",
"Nane garis ne tu nan e, bila kes nebeje ev mal be evaran e (arvan e).",
"Nane gilgil_ (u) zîlika pîvaze. Nane Iso dixwe, selawetê li Muso dide. ",
"Nanê min, qesasê serê min. Nanê pehtî, siltanê ser textî. Nanê tîrê, xwes hevîre. ",
"Nano ziko dixebite. ",
"Nav giran, mezel weran. Nav nuçikan ledike. ",
"Navbera jin u meri, bîra niherî. Navbera min u kîjan cinaren min xira bibe jina min diçe li ber dere wî tesiya xwe direse. ",
"Navbera wan sar buye. ",
"Nave gur derketiye, rovî dine xera kiriye. ",
"Nave me giran e, ware me weran e. Nave min li te, qotik li sere te. ",
"Nave wî/ we hildide, hezar nav ji dev derdikeve. ",
"Nave wî/ we nayne ser zimane xwe. Navî giran e, bajarî weran e. ",
"Navî mer e, kunde kor e. Navika wî avetine nav malan._ Nayne ser bare xwe. ",
"Ne berxtî ter sîr vexwar, ne kavirtî ter gîha xwar. ",
"Ne bi halekî, ne bi malekî, tu çi zanî ewhalekî. ",
"Ne bi kerî seve, ne bi kerî sive te. Ne bixwe ne bistîne sev u roj le temase bike. ",
"Ne dibe ere ne dibe na. Ne dibe him, ne dibe gim. Ne dide ne distîne. ",
"Ne digirî tu pe ra bigirî, ne dikene tu pe ra bikenî. ",
"Ne dixwe ne dide hevala, genî dike daveje newala. ",
"Ne dixwim gelaza, ne didim hevraza. Ne dixwim nane te, ne dajom   horika_ te. ",
"Ne dixwim saware, ne diçim heware. Ne dixwim virika, ne dajom horika. ",
"Ne doste fileh, ne hespe qule. ",
"Ne feqîre bitir, ne dewlemende diz ne maqule derewîn. ",
"Ne feqîre poz bilind, ne mevane malbigund, ne jî mirove ku di civate de beje jina min rind. ",
"Ne gunde be rez, ne kone be pez ne mere beje ez u ez. ",
"Ne gure gura ewran e, ne hire hira hespan e. ",
"Ne hejayî kapekekî Uris e. ",
"Ne ji bilike, ne ji holike. (dibe) Ne ji dere dibe ne ji mizgefte. ",
"Ne ji dere dibe ne ji vange. ",
"Ne ji Hemzan e, ne ji Meman_ e zirape wan orta ne. ",
"Ne ji mehna buya, rovî we li sukan   gerha buya. ",
"Ne ji xîrete, ne ji omete. ",
"Ne jina belas, ne xulame be meas ne jî erde kas. ",
"Ne jina bi kildan, ne mere bi dev giredan. ",
"Ne ker ket, ne hîz dirî. ",
"Ne ker li garane, ne pirsiyar li gavane. ",
"Ne ker te ber bar, ne bar diçe ber kere. ",
"Ne kere min e, ne gaye te ye. ",
"Ne kifkifa nefsî, ne çip çipa dolabe. Ne li mine, ne li teye. ",
"Ne li we heke u ne li we qedqide. Ne li xera te, ne li sere te. ",
"Ne male min, ne cane min. ",
"Ne male pir, ne gerdana stur, male pir zu ziyan dibe, gerdana stur zu zirav dibe. ",
"Ne male, ne li teye. ",
"Ne mere sermok, ne jina  kenok. Ne newala kur radizem, ne xewnen xirab dibînim. ",
"Ne pîre bas kir li ser gunî runist, ne jî gunî bas kir pîre re çu. ",
"Ne sora ber agira, ne rinda be çira. Ne Tahir e, ne Zahir e, her yek gurekî har e. ",
"Ne xema min e, ne dema min e, qirçe qirçe benîste min e. ",
"Nediçu dawete, dema diçu digot: “Lot ha lot.“ Neditya dît, xwe de rît. Nefsa xwe kor kiriye. ",
"Netika xwe dide netika wî/ we. Netika xwe kiriye gile. ",
"Newroz, xilas bu dew u doz, me dibît herî, nedibît toz. ",
"Nexwas e, parî xwes e. ",
"Nexwasa sekseke (çileke) danzdeh nan avet keleke.",
"Neynuk (nenuk) nemaye ku pe xwe   bixwerîne. ",
"Nezanî, rehet canî. ",
"Nikare beje ez kafirim, an misliman. Nikare bi kere, dibeze kurtan. ",
"Nikaribun bi yen beredayî, çun yen giredayî. ",
"Nimej e xewlekî dur direj e her kes nikare bibeje. ",
"Nîne bixwe nan u jajî xwedî dike tole u tajî. ",
"Nîsan e çipik (çilkek) bi kîsan e, li dere hemî kesan e. ",
"Nîsan e, buka salan e. ",
"Nîsika pîre, nadim birince mîre. Nivista be tist te mele kust. ",
"Nivista be tist, xwediye xwe kust. Nivistek çekir ji qîze re, gu hat bi mîze re. ",
"Niyeta dil, qeda serî. ",
"Nizane mala dawete, dest daveje kevçî u diçe. ",
"Noka genî çu bajer, bu leblebî. ",
"Pale qels e, hencet das e. ",
"Par li me dida dara, îsal xwe nagire li ser çardara. ",
"Para geroka, çu ber balisoka. Pariye pirî, gewrî dirî. ",
"Pariye xwe xwes kir, ruye xwe res kir. ",
"Pars kir ber deriya, da xera miriya. Parsa vî welatî nebe bila parsa welatekî din be. ",
"Parsek e, bu sur u qetek e. Pasî ji dest çuye. (Çu) Patika hustiye xwe xwerand u çu. Pel guhe xwe dike. ",
"Pel mala cuna kiriye. ",
"Pella ledixe, giliya je derdixe. ",
"Pella li min nexe, pirsa ji min dernexe. ",
"Pella tîne bîra diza. ",
"Perda ber çave we/ wî tune. ",
"Pesa min de runistiye, li ruye min da darda buye. ",
"Pesiye diçim gezok e, pistre diçim tîzok e. ",
"Pesiye diçim pel peniya min dike, pistre diçim pehna daveje min. ",
"Pey miriya kesî xwe nekustiye, wey li cane çuyî. ",
"Pey tire, min kezî kure. Pez tune run difrose. ",
"Piçuk li cihe xwe, mezin li cihe xwe. Piçukaye diben hek, mezin dibe diben qaqe. ",
"Pir gotin, ciger sotin. Pir kire hindik xware. ",
"Pira selawate weke derzî, salih li ser ra bezî, fasiqan çok le lerizî. ",
"Pîra Same tevî ame. ",
"Pîre bawer nedikir mer bike mer dike pel heystoka dike. ",
"Pîre ji tendure çu ber kulfike got: “Xwede xerabike ez çiqas erd geriyam.“ Pîre payîze çu ligate. ",
"Pîre ter bu ji kîre, du re sewî hatin bîre. ",
"Pîre tir kir adare gîsik filîtin bihare. Pîre tir kiriye u pîre ne raziye (qaile). Pîrî, hezar eybî. ",
"Pist pe gireda ye. Pista wî naye erde. ",
"Pista xwe kutaye çiyaye bilind. Pista xwe rast nake. ",
"Pista xwe tu kesî de nake. Pistî barane ga bi cil dike. Pistî kurî, pir vedibirî. ",
"Pito ye berane qor e, sîng vedaye xwedaye ber e. ",
"Pîvaz pîvaz e, çi sor e çi sipî. ",
"Piye xwe ji berika xwe zedetir direj dike. ",
"Poste conega li ser pista ga ye, poste ga conega nikare bikisîne. ",
"Poz le  nake. Poz le nasewite. Poz pe nake. ",
"Poze xwe dixistiye. ",
"Pozî wî/ we hat mizdan. ",
"Qaz bi mesa wardeke çu ket qalça we ji hev derket. ",
"Qazî bi xwe çu pek neanî, muyek ji ruye xwe bi rekir. ",
"Qaziye zarokan xwe xeniqand. Qedire gule çi dizane, kelbes_ dive kere res. ",
"Qelene mirtiba dide, qîza esîran   dixwaze. ",
"Qenc li me rast nayen, pîs li me danayen. ",
"Qesem nave xwede ye. ",
"Qet denge meqese li ser neketiye. Qet deste xwe neso u tev ape xwe nan nexwe. ",
"Qet nayne ser bare xwe. Qet qusa xwe le naxe. ",
"Qet xwîne ji xwe bernade. Qey (ma) beq dixesandin? Qijik nikulê xwe lêxwe, tistek pê ve nayê. (Qijik nikulê xwe lêxe  piçikek gost dêv ve nayê) Qirdê me kor, bextê me res. Qirse xwe nadim li ser bende wî. ",
"Qîz be tu zanî, jinebî be ez zanim, jina berdeyî be sere hespe min berde ez herim. ",
"Qîza bas, pey bibe kas. ",
"Qîza wî ya keçel mir, got: “Wey li min gulî direje!“ Qîzan re neçin qize ter in, jinebiyan re neçin zef digerin, dayiken dergusan re herin, zu vegerin. ",
"Qîzanî çiqas xwes e, bukanî gula ges e, gava ku ket ber qehra malan, roja res e. ",
"Qîze sor in, xorte kor in.",
"Qîzek nazand, gundek bezand. Qîzike mer kir, kofiya xwe xwar kir. Qolibe mesa ye, denge sesa ye. ",
"Qun bu, qun jî çu. Qun kutane hev. ",
"Qun quna mirîske ye, hek heka qaze ye. ",
"Quna tazî, tembure dixwazî. ",
"Qune dixwazî, qalibek sabun jî ser da dixwazî. ",
"Qurbana wî cîhîbim ku tirs le hebe. Quze delegure peva ye. ",
"Radibe hut e, rudine kut e. Rast u çepe wî/ we ne kifs e. Rast, xilas. ",
"Rasto bi rastiyo, xwaro dare sikestiyo. ",
"Rasto dirusto, xwaro sikesto. Rebiro, kur piro (biro). ",
"Reç reça kere ye, fel fele Pere ye. Res e res e, qawike jî. ",
"Res e weke qîre, rast e weke tîre. Rese tu li vir bisekine eze gewra bigerim; ku min gewr nedît tu dîsa resa minî. ",
"Rewîtî xwes tist e, le çirte çirt li pist e. ",
"Rih direj e, dil qirej e. ",
"Rihe xwe diqusîne, du re eynike tîne. ",
"Rim li tur hilnaye. Rindeke gundeke. ",
"Rindî rindî geroka li nava gundî. Riske wî ji bune spî. ",
"Riya mala mirine ye. Ro bi ro, xwezil bi do. ",
"Roj bune sal, zik bune çuwal. Roj çu edî venagere. ",
"Roj ewravî sev sayî: Sal xirab, jina ciwan mere kal: Mal xirab. ",
"Roj ket aliye Merdîne dewara bajo kadîne; roj ket aliye Cizîre dewara bajo ber nîre. ",
"Roj li cîhkî teng me (le) bu evar. Roj li me çu ava. ",
"Roj li min xerab çu (çuye) ava. Roje heft xusuya dixeniqîne, bi sev qurquroneka derî ditirse. ",
"Rojiya bin teyste girtiye. Rojnîvro xewnerojkan dibîne. ",
"Rovî ji barane bitirsiya ye ji xwe ra ewayek çebikira. ",
"Rovî kirine sahe mirîskan gotiye: “Kene min te, aqile min nabire.“ Rovî nediçu qule, hejek jî bi boçika xwe ve gireda. ",
"Rovî re revî, re rovî revî. Rovî ter e, tirî tirs e. ",
"Rovî tu çima xwe dihejînî? Got: “Li min te u ji min te.“ Roviye newala, bu xwediye mala. Ru da , cîh da. ",
"Ru daye, derkete ser serî. Ru reso, parî xweso. ",
"Ru u simbel buye tev hev. ",
"Run dest de be ro dike (dirijîne)te. Rune genî, li ser nane xwedî. ",
"Ruto ha vî alî ave, ha wî alî ave. Ruto, xeber puto. ",
"Ruye res çi hewceyî teniye ye?   Ruye res u sipî we ji hev kifs bibe. Ruye wî nagire. ",
"Ruye wî qewîm e. Ruye wî/we naese. ",
"Ruye xwe daye bin piye xwe. Ruye xwe je zivirand (guherand). Ruye xwe res kirî ye. ",
"Sa berî hev didin. Sa riye, ga cuye. ",
"Sal bi sal, xwezî li (sala) par. ",
"Sal ew sal e le bihar ne ew bihar e. Sal mij e, kodik tije. ",
"Saq e, laq e. ",
"Sar u serma ye, cilik bav u bira ye. Saro baro bu. ",
"Se kela_ bi kevirekî waldigerîne. Se xatir tune, xwedî xatir heye. ",
"Sebir mine rehman, ecele kare seytan. ",
"Sebriyo, debriyo. ",
"Sed çakuç u yek zindan. ",
"Sed sal u saetek, saetek u sedsal got: “Rast e pistî du kur u keçeke.“ Sehme ser da girtiye. Seqa,_ li gorî heqa. ",
"Ser berjerî, qun hevraz. ",
"Ser da tasek ava sar vexwar. Ser eyare wî agir dadan. ",
"Ser guhe wî/ we pelixandin. ",
"Ser sere xwe u heft bave xwe razî ye. Ser serî de tasek ava sar retin. ",
"Ser sofi ye dil kafir. ",
"Ser ve Ellah, bin ve Neuzibillah. Sere be es. ",
"Sere ço bi gemar, bine ço bi gemar. Sere kere zike zebes. ",
"Sere ku neese çi hewceyî benda ye? Sere lode girt. ",
"Sere me sere xernediyan ji qirsika hatin. Çun zereguniyan. ",
"Sere min bi ard dîtiye hew dizane qeras im. ",
"Sere min bi zer e, beyjna min bi sehr e, dile min bi jehr e. ",
"Sere min sere xernediyan e. ",
"Sere min seh kiriye, derziya min jî li ber ra ye. ",
"Sere wî ber da ma. (Sere wî ket ber.) Sere wî bi ard ji as be, kes je bawer nake. ",
"Sere xwe di ber xelke de diskene. Sere xwe kiriye curnekî vala. ",
"Sere xwe pe naesîne. ",
"Sere xwe veke, deyl bexte xwe ke. Sergoto ber barane, pexwaso ber garane. ",
"Serhingî di bare kere daye. Serî gir e, bar nebire. ",
"Serî ji eqil diese. Serî le giran buye. ",
"Serî quç e, binî puç e. ",
"Serî sahîtok, binî tije buhok. Seriyo tu qurbana lingan bî. Serpe petin, ser hev hatin. ",
"Seva çe, para hirçe. ",
"Sevek li dare ye, çave her kesî le ye, kes nizane qismete ke ye. ",
"Seyda xwe nake ji herdu eyda. Seye belek maqule sa ne. ",
"Seye me ye, li ber dere xelke direye. Seye soro gurî va ye. ",
"Sibat hat u buhurtî, nav dile gîsikan bez girtî. ",
"Sibate bang kir adare got: “Se rojan bide min bi deyn, eze gîsika ji tehta bînim xware.“ Sibhan ji wî xaliqî dudo li hevdu aliqîn, yek kor, yek çav siliqî. ",
"Sim sima kere ye, fel fele Pere ye. Simbel li pisîkan va jî heye. ",
"Simbel poseyî, mal mirtib. Siwar ji me qeda ji Xwede. ",
"Siwar siware Tirkan, qeda ji Xwede. Siwaran siwar leqandin, xal kotiyan xwe bi qusa hespan xapandin. ",
"Sofiye remezana mîna kere (li) garana. ",
"Sole seytin çep dixe lingan. Sond bixwe, serî naese. ",
"Soro moro bu. ",
"Soz yek e, nabe dudo. ",
"Suk u ya suk, sok u bersok tev de ev e. ",
"Sura xwe daye, bawerî pe anî ewî jî bi siwarî da ser xanî. ",
"Suret paç e, ya ji dil naçe. ",
"Şal hesîn e, tistek di mal de nîn e. Sam dur e, ma misar jî dur e? Şana_ hingivî ye, bele ne serînkirî ye. ",
"Şayî sayî gotî, sîn sîn gotî. ",
"Şeb u sekir çun Diyarbekir, sekir runist denge xwe nekir, sebe rabu pesne xwe kir. ",
"Şebes bi denge xwe, hinar bi renge xwe. ",
"Şeh u mirak (eynik) eywelleh. Kar u sixul na welle. ",
"Şekir naxwim, pîvaz  dixwim. Seko peko, nave xwe li hevale xwe ko. ",
"Şer da xal u xwarzî, sorbe da ap u birazî. ",
"Şerbik nu ye, av serîn e. Sere man u nemane (ye). ",
"Şev bu, seva res bu, miya qer bu, berxek li ber bu, li ser berxe çilkek xwîn bu gur ew tev de dî bu (dîti bu).",
"Şev li pist e, sixul ne tu tist e. Sewqa wî daye newqa wî. ",
"Şewra jinan, beriya bizinan. ",
"Şex saf_ be u xilme av be u keçik u kurik aza bin pa eva nabe. ",
"Şeytan gotiye: “Ye ku li xwe biheyire ez di wî im.",
"Şîn u sahî, hevalrewî. Sîre kera metî ye. ",
"Şîre min bila çe be, toye min bila pak be. ",
"Şîre ser e, di eyare berazan da ye (donxizan daye).",
"Şîre zikmakî ji firnikan ra anî. Sivan u gavanan hore-hor e ewan watre dinya kore. ",
"Şox u seng e, bi nav u deng e. Sujina di çave xwe de nabîne, derziya çave xelke de dibîne. ",
"Şuna mera, mane kunde dera. Sur simbele nabire. ",
"Şure qetle li deste te, rehma Xwede li dile te. ",
"Şure tazî, xwîn dixwazî. ",
"Şustin vesustin reng u ru, xwarin vexwarin gendi gu. ",
"Şuxul bu dor,  ocax  bu  kor. Suxul ji min re bike, ji xwe re hîn be. ",
"Şuxule havîne zivistane dike. Suxule kirî pîxem ledixe. ",
"Tajî jî dibeje: “Ya Ellah!“ Kewrosk jî dibeje; “Ya Ellah!“ Takî je bikisînî we sed pîne je bikeve. ",
"Talane meru ye, liva cehî ye. ",
"Talasa gure ku qantir (hesruk) biha ye. ",
"Talihe xelke res e, talihe min res u bes e. ",
"Taliya tire, min kezî kure. ",
"Tase gote legane: “Pîsa resa dev pene, lawike min bu tu dane.“ Tasek dew, nanekî cehîn ne tistek e, ba li pista mere xerab keve. ",
"Tastiya wî li ser pista keruske ye. Tazî ji jina xwe re got: “Zirav birese.“ Te çi xwar losî can be, te çi dît ji me   ra beje. ",
"Te got kew e, min got nikile we sor e. Te got mirî tira nakin! Te he ginikres  nedîtine. Te hela he maste ser bi sîr nexwariye. ",
"Te kef kir, ez ketim belaye. ",
"Te ku da ave, ha li çoke, ha li nave. Te sere min xwar Te sotin le naye gotin. ",
"Te silk jî divet, kutilk jî divet. ",
"Te sust ava bi gu, ez çi bikin qenciya bi du. ",
"Tehte te le rî, barane sust. ",
"Tekeve zike diya xwe xwe xilas nabe. Temahkaro, gunehkaro. ",
"Ter nedixwar nan u jajî, xwedî dikir tole u tajî. ",
"Tev u tesiyan ra na welleh, qulopon re eywallah. ",
"Tevir got dare: “Ez hatim te! Dare got: “Ez çi bikim destiye te ji min e.!“   Tevn birî esa serî firî.",
"Tevn hate dara, namîne li wara. Tevn u tesî dile min desî, diçe ave çirtik dave. ",
"Texte min gelek mixan hilnade. Teyr difire bi refe xwe re. ",
"Teyrek hebu teyra gistî li ser wî de zîrç dikir ewî jî li ser çeliken xwe de zîrç dikir. ",
"Teza dibînin, kevna ji bîr dikin.  Teze diya mine çoka xwe dayne erde ji min ra birakî bîne. ",
"Teze hatin, kevn xelat in. Tî dibe ave tî tîne. ",
"Tif kirine beqe, beq li wan keniya u got: “Ruye min bi ava behre sil nabe, we ji tifa we sil be?“ Tifa li ser hevraz e. ",
"Tilî peçiyen wî zer dibirin. Timawo ji hevalan mawo. ",
"Timaya çarixan kir gore qetand. Timayî, re mayî. ",
"Timî bere kevçî berve xwe dike. Tir ji Qeyso re kir eyb. ",
"Tir li hemama, derew li xerîbiye. Tir li ku, das li ku! Tîra ji mine, li mine. ",
"Tira par havîne, îro hatiye sîne. Tira pîre ya du çiqil deve mere be aqil. ",
"Tirba daye xwes çekir le kelike we de rî. ",
"Tirba nezda miriya kîjan e? Tirba siwaran her kola ye. ",
"Tirsa mirine ketiye dil. ",
"Tiste nedîtî u nebînayî. (Tisten nemayî.) Titî ku sar dibe, dibeje: “Eze xanîkî ji xwe re bigirim.“ Tivinga deste te, tu tesiya diya te ye? Toroqa wî dan ser nane wî. ",
"Tote totavinge, li te sele min bejînge. Tove xweziye çandin li sune, La   hewla Wellah hesîn bu. ",
"Tu benike sor u zerbuyayî, te bi dere hebana xwe ve buyayî. ",
"Tu bi hirî ba, te li nav kerî ba. Tu bi ve quse, naçî Muse. ",
"Tu bi vî aqilî herî, tuye keweke hesîn ji xwe re bigirî. ",
"Tu bibî gerdî, tu nebînî wî erdî. Tu bidî zîtika nedî zîtika, te bidî heqe dîzika. ",
"Tu bikî nekî Xwede bide te. ",
"Tu çawa siware exteyî, te çawa nivîne xwe bazirgan ra hîstiye? Tu çi bejî li bejna hespe min (heyren) te. ",
"Tu çi zu buyî dîk, te çi zu bang da? Tu çi zu buyî kundir, te çi zu sax veda? Tu di bin kume mindayî. ",
"Tu dibejî deve te mor kirine. Tu dibejî ji deve gur derketiye. ",
"Tu dibejî ji nexwasan ra çuye berfe. ",
"Tu dibejî li ser diranekî çeriyaye. (çeriye) Tu dibejî qey demana dare ji te dixwazin. ",
"Tu dixwî, li min digivire. ",
"Tu dizanî ke tuyî (tifî) deve wî/we kiriye. ",
"Tu gistî ser hev de bikutî nabe sîr u pîvazeke. ",
"Tu hatiyî agir bi deyn bibî? Tu he rastî helikresan  nehatiyî. Tu ji bîhr bikî, Xwede ji bîhr neke. ",
"Tu jî dizanî ro xerab li min çuye ava. Tu ji sa ra çarixan bidiruyî we çarixen xwe bixwin. ",
"Tu ji vir ve çuyî gizim, ji we ve hatî nizim. ",
"Tu kere lexî, xwîn je naye. ",
"Tu kîjan kevirî rakî (hilkî) ew ji bin derdikeve. ",
"Tu li serî u sosina li desta u bazina Xwede ji hinekan distîne dide hinan. ",
"Tu li Soro dixî, Moro ji xwe ditirse. Tu me je re gotiye hespe te ker e? Tu min bixwerîne, ez jî te dalesim. Tu ne mala he he ye ku her roj be. Tu nesekirînî, nan sela te napeje. ",
"Tu poz bigirî, ruhe wî/ we ye bikise. Tu qala ke bikî an li ber derî ye an ser xenî ye. ",
"Tu tera xwe tirî digerî an, kustina nehtor digerî? Tu tist naye ber çaven wî/ we. ",
"Tu xwes mevan e, le ne tu mazuvan e. ",
"Tuyî deve hev kirine. ",
"Va dar, va birek Va dil e, ne bilxur e. ",
"Va ev ez, va ev jî kefene min. ",
"Varik e, heke hesinî dike. ",
"Ve ave guse guse, kes nabeje dewe min tirs e. ",
"Vedikeve las e, radibe bas e. ",
"Vî destî dide bi wî destî distîne. ",
"Vî guhî dikeve, wî guhî re derdikeve. W ….",
"War ew war e, le bihar ne ew bihar e. ",
"Warin dewe min biken, ez jî herim dewe mîr bikem, bila mîr kevnekiraseke bide min. ",
"Way tirmixa kure kere! We ev hevira hin gelek ave hilîne. Wek agire bin kaye. ",
"Wek ase av li ser birî. Wek ava arane. ",
"Wek ava bin kaye ye. ",
"Wek benîst pe ve dizeliqe. Wek berfa spî. ",
"Wek berxa ber bizine. Wek berxa ber du maka. Wek berxa ber guran. ",
"Wek bizina ku li ber ecele xwe bireve. ",
"Wek buka barane. ",
"Wek çeleka ji ber golika xwe newan bibe. ",
"Wek çeleka pel golika xwe bike. Wek çeleka pel pizdana xwe bike. Wek dela li ser tula. ",
"Wek dela tu tulen we jî ber bigirî. Wek desmala ser destan diguhure. Wek deva du cîhî de be serjekirine. Wek deva ji palane xwe bixwe. ",
"Wek dîke bewext bang bide. Wek dîware li ser buze. ",
"Wek Eceme ku li çav penere ter bikeve. ",
"Wek etîmen çav heke sor ketî. Wek eyare genî ku bihn je be (te). ",
"Wek feleka xapxapok. Wek fira kewe. ",
"Wek garise li ser defe. Wek gawiran xebatkar e. Wek gura diberî dikin. ",
"Wek gure dev bi xwîn. ",
"Wek gure di keriya mîhe de. Wek gure di keviya mîhe de. Wek guze bi jimaran. ",
"Wek hespe Sidhana_ pas ve diçe. Wek hirça birîndar. ",
"Wek hirça deve geliyan. Wek hîva çardeh salî. ",
"Wek kefa deste xwe dizane (zanim). Wek kefa deve seye har. ",
"Wek kefa sabune. Wek kere guh sist. ",
"Wek kere ku ber ve gur bizire. Wek kesteke hale kevir de bigirî. ",
"Wek kevçiye nesustî xwe daveje nav. Wek kevire bine bîre. ",
"Wek kewen tiving li ser teqyayî. Wek kore keç bikeve dest. ",
"Wek kore riya kaniye nas kirî. Wek kusiye ku qalike xwe qayîl nebe. ",
"Wek liva nîsike, ne ber e, ne pist e. Wek mar e, ne cîh e, ne war e. ",
"Wek mara pe veda. ",
"Wek mara, bi axe didebire. Wek mare di tur de. ",
"Wek mare pî di zik de. Wek melaye nexeritandî._ Wek melaye nexwendî. ",
"Wek mesa ku bikeve nav lepe kora. Wek mesa ku li ser gamese dayne. Wek mirîska melisok. ",
"Wek miske ku tekeve qula mare res. Wek muye ji mast bikisînî. ",
"Wek pele nav gu ketî. Wek peza ji kerî qetyayî. ",
"Wek peza li ser diranekî biçere. ",
"Wek pisîka pelur di ser de hursiyayî. Wek roviye ku bendî punda mirîska bikeve. ",
"Wek sere vepincirî. ",
"Wek seye xwe ber barane sil bike. Wek terale Bexdaye. ",
"Wek teyre di mij de berî kewan de. Wek zerika heke. ",
"Weke guza kor e. ",
"Weke ku tu pifî çire bikî u vemirînî. Weke muma helandî (helya ye).",
"Weke nane sele du ru ye. ",
"Weke pisîkan e, li ser piste nakeve. Wekî hirç ji mese, derket çi ner çi me. ",
"Wel axirî, wel aqubet. ",
"Wexta ciwan bu ew bu çelenge siwara, wexta ku kal bu, ma li dewsa wara. ",
"Wexta heye mevanî, wexta tunebe golikvanî. ",
"Wexta kara ru digerîne, wexta sivre kevçiyan tîne (digerîne). ",
"Wexta ku ez ciwan bum, bi tîr u kewan bum; ku ez kal bum, bendeware   nane sikeva bum. ",
"Wexta nîçîra min te guye tajiya min te. ",
"Wexte gîha bu, kes ne xuya bu, dema bu firîk, Hemo u Heso bun sirîk. ",
"Wey le min çav bi susek xwe ve mizdayî. ",
"Wey li qune, way li meska dosafe. Wez weze Musa ye, fel fele Firewun (e). ",
"Wî li min daye, ew digirî. ",
"Wî tim dewe tirs vexwariye, çi haya wî ji dine heye? Wisa direje ku tastiya ewran dibe (dixwe). ",
"Wisa qirej e, mar je vedirese. Wisa sar e, wek suka sehare._  Xal Xidiro, hero li viro. ",
"Xalan xwarzî rakirin, maman birazî winda kirin. ",
"Xate wisa dibeje, hela ka Fate çi dibeje. ",
"Xatiya Bihare, te gileya pener xware em tev derketin bihare. ",
"Xelayî hatiye, tu camerî jî hilatiye? Xeletî ji piçukan, efu kirin ji mezinan. ",
"Xelk mal u dewlete çedike, ez u Androkoloze xwe tuj dikin. ",
"Xelke gistî girtiye yare, bexte min rebenî tene buye hewar e. ",
"Xelke ra gul e, ji min ra sil e. Xelke re edet e, ji min re erbet e. Xelke re masî giro, ji xwe re kusî giro. ",
"Xelke re pirbejo ji min re ker u gejo. Xelo, xellas! Xema berfe ye ku debara kasiba tune. ",
"Xema kor e, çira wesiya. ",
"Xemla buka, buka çuka. Xer ji xere derbas buye. ",
"Xer u xwesî li te barî, kevir u kuçik li min barî. ",
"Xera ku ji te te, bila ji Xwede be. Xew nema li piçuka, abur nema li ruye buka. ",
"Xew xwes e li çayire, ber zinaran, le wekî mar tune be. ",
"Xewa pir giran, meriye pir nezan. Xezale ji ber sikevlatoke, zozan li xwe heram kir. ",
"Xistiye benîst, deve xwe de dicu. Xofkeso, qeda peso. ",
"Xort revîne kera, qîza gotin: “Ya me ma bi Xwede.“ Xurte ne bi male xwe. ",
"Xwe bi sîreke te didî, bi heft pîvazan nikarî je xilas bikî. ",
"Xwe bidî tîzan nedî tîzan, te bidî heqe guzan. ",
"Xwe çedike, xwe pak dike. ",
"Xwe da rîti bu digot: “Min bi rews   bison.“ Xwe daye ber bere res. ",
"Xwe di kara xwe de, ker di nav naxire de, tu dibejî: “Ha werin xwe, ha werin xwe!“ Xwe gir  dikuje. Xwe giran digire. Xwe je re dagirtiye. ",
"Xwe je re dike erd u xwelî. ",
"Xwe ne ji dere dike, ne jî vange. Xwe serîn dike. ",
"Xwe vedigere. ",
"Xwe weke baz e, le neçîra wî ji xelke ra ye. ",
"Xwe winda kiriye. Xwe zede dibîne. ",
"Xwede beje kane, ez bejim hane. Xwede bike, qule çi bike? Xwede çiyan jî tene neke. Xwede daye, mirde zaye. ",
"Xwede dikare qir jî bike, pir jî bike. Xwede diya meriya dide ser zereguniya, kere Same jî berdide ser. ",
"Xwede felen mar dizane loma dest u pe kirine zik da. ",
"Xwede gir bide te, neynuka jî ji te bistîne. ",
"Xwede got: “Xwe bisitirîne ku ez stareke li ser te bikim.“ Xwede gotiye: “Dewara xwe bi lingekî gireide, se lingan jî bispere min.",
"Xwede gotiye: “Ka te eyba xwe vesartiye ku tu eyba hevale xwe dibejî?“ Xwede gotiye: “Xwe ji ber diyare ketî bidin alî.“ Xwede kor kiriye, pel agire sor kiriye. ",
"Xwede ku da yekî, gere bizanibe   bixwe. ",
"Xwede ku mirov kor dike, mirov linge xwe li kodika xwe dixe. ",
"Xwede mirov ji hespe peya neke, li kere siwar neke. ",
"Xwede nede dijmine min. Xwede nede serme. ",
"Xwede wan (me, wî/ we) xwedî dike. Xwedî kir bi deste xwe, kir  emele sere xwe. ",
"Xwediye fise bi xwe dihese. ",
"Xwediye gost ji dizane gost heram e, xwediye pera jî zane pere qelp in.",
"Xwediye kela Potike, tu xwe baveje ser jinike, sibe rabe bike sîna ge, çeleke u golike. ",
"Xwediye mirîska, zîrç li enîske, were male bixwe zerhevrîska. ",
"Xwediye sebre, mîre Misire. Xwediye seve sev nexwariye. Xwediye skure ew e. ",
"Xwediye xanî deng nake, kirecî lev nake. ",
"Xwelî li axe, çaxe piskul bu malxe. Xwelî li wî serî, ewî ga da bi kerî. ",
"Xwes xeber e, le min je ne bawer e. Xwezî bi aqile pasîn. ",
"Xwezî bi nave we ne di nav we. Xwezî buka xelke xerîbama u min pesne mala bave xwe bida. ",
"Xwezî mirin hebuya, kalbun u pîrbun tunebuya. ",
"Xwezî sewiya, ne hewiya. Xwezî virek bikira tirek ji pera bikira. ",
"Xwezî xesu nebuna, buk bi dile xwe buna, qirç qirç benîste xwe bicuna. ",
"Xwîn li ser de dikele. Xwîn ser de hatiye. ",
"Xwîn tijî çav(an) buye. ",
"Xwîna xwe kiriye kevçî, raberî min dike. ",
"Xwîne di ber neynukan de avet   (avetiye). ",
"Xwîne pe girtiye. ",
"Ya dile min bila dile min de bimîne. Ya ji min we da, ye min te da. ",
"Ya ku hat bîra min, hat sere min. Ya ku xwede dizane çi ji qulan veserim? Ya mera lehatin. ",
"Ya zare te ji min re, ya dile te ji te re. Yan eshed, yan nan u to. ",
"Yan mam, yan xal. ",
"Yare diya min yekbana mine bi dendiken behîva xwedî bikira. ",
"Yare ji yare serm kir, warres ma. Yare ji yare serm kir, zare kurîn di pesa xwe de nedît. ",
"Ye bastir Behdîn e, ew jî hîz e, diz e   u derewîn e. ",
"Ye bi ar ji xwe fedî kir, ye bear got, ji min ditirse. ",
"Ye bi dew çu ba ye be dew alîkarî xwest. ",
"Ye birçî çu ciwate, ye tazî neçu. Ye der hat ye hundir gewirand (qewitand). ",
"Ye derewîn vala hilda, ye rast tijî hilda. ",
"Ye dewletî keremke mele, ye kesib bimîne dere male. ",
"Ye direve jî gazî Xwede dike, ye dide pey jî gazî Xwede dike. ",
"Ye jinan hatin ber ara (agira), ye meran çun ber dîwaran. ",
"Ye ku heviya yare ma, heft salan be jin ma. ",
"Ye ku min hilnade terkiya hespe xwe ez hilnadim terkiya seye xwe. ",
"Ye ku xebitî, nexelitî. ",
"Ye ku xwe pesinî, tir te de nesekinî. ",
"Ye ku zane ji xwe zane ye nizane dibe qey baqe nisîkan e. ",
"Ye leheng (qehreman, xurt) ewe ku hesin sor bu, rahele. ",
"Ye li bin deng nake, ye ser qare qar e. ",
"Ye ser sekiniye, ye binî nasekine. Ye te çilul u milul, ye min Xwede u Resul. ",
"Yek bi male xwe, yek bi cane xwe. Yek dimire, yek dimîne. ",
"Yek e, le pir bi dendik e. ",
"Yek heft salan be kiras ma, je re kiras kirîn got: “Zu bidirun“ u revî ket tendure. ",
"Yek li xwe kire duda (duduya). Yek merî, bi hezaran xiyal. ",
"Yek sahide dehan e. ",
"Yeke çav belek e, qijeleyî befeyde ye. Yeke dilî, yeke zarî, bigire  baveje nava narî (agirî). ",
"Yekî aqil, yekî din, xwe dan muyekî neqetandin. ",
"Yekî darek da yekî bi guliskeke  Yekî du gaye wî hebun, yek nediket hundir, yek jî ji hundir dernediket. ",
"Yekî je distinî bi dehan je xelas nabî. Yekî Qerazî, yekî Berazî, ji hevdu re bune xal u xwarzî. ",
"Yekî ra jî ho, hezarî ra jî ho. ",
"Yekî re gotin: “Tu bext dixwazî an text?“ Got: “Bext ku hebe, texte bi xwe be.“ Yekî re nifira dikî beje: “Xwede male te teke pere u pera jî di berika  teke.“ Yekta nebe, duta te ra nabe. ",
"Zad u ziwane tevli hev dike. ",
"Zad zade miriyan e, gost goste sa ne. Got: “Xevzank bi xwe jî ji kîre   filan e.“ Zane dawet e, le nizane mala ke ye. Zar doste pist hisk. ",
"Zaroyen du pinda, weke riya here du gunda. ",
"Zavaye me çi zava ye, qîra sîr e li me geriya ye. ",
"Zavaye me çi zava ye, teniya don e li me geriya ye. ",
"Zebes e, dendik res e, çiqas xwes e. Zer da bi zer, kirkirk jor de daser. ",
"Zik li piste ve girtî ye. ",
"Zik ter dibe sturiye xwe li kendalan dide. ",
"Zik ter e, çav birçî ye. Zik ter e, mil ser e. ",
"Zik ter e, xew je re xer e. Zik u pist buye yek. ",
"Zike wî sen e. (sen buye) Zikekî ter e, deh zikan birçî ye. ",
"Zilam ji pîreke, gaye cot ji çeleke. ",
"Zilam li ser kar e, pîrek li bin dar e. Zilam zilam e, pîrek pîrek e. ",
"Zilamek hebu, dema nane wî hebu dewe wî tunebu, dema dew hebu nan tunebu; dema herdu jî hebun ew ne li mal bu. ",
"Zîlike bihare, debara male. Zilm zilma Xwede ye, ferman fermana axe ye. ",
"Zilmkaro, dinya xwaro. Ziman girtî, ser rehetî. Ziman sor e, hereket kor e. Zimane mara ber derxist. ",
"Zimane sor e, pesî (pesiye) ne geli ye ne zihor e. ",
"Zimane wî nebuya, qijikan we çaven wî derxistina. ",
"Zimane xwe birî, cîhe xwe kirî. Zimano leq-leq, seriyo teq req. Zivir zivir, dîsa li vir. ",
"Zivistan hat birka_ feqîran teqiya. Zor nagîheje kere, palan dikute. ",
"Zor zane zer zane deve tivinga mor zane. ",
"Zotike we/ wî ji sere hefte heft bave we/ wî zedetir e. ",
"Zu bajo, hur bajo, dur bajo, ga meesîne."]