export const proverbs_only = ["Agir bi qurmiga dimîne",
"Agir digire mala hinan...Hin kewê xwe ser dikizirînin",
"Agir digire rêrê ter û hişk têk de dişewite",
"Ahê vî destî namine li vî destî",
"An naçe êş...An diçe, aşvên dikuje",
"An talan dike an şivên dikuje",
"Aqil ne ji kiçikayî û mezinahî ye",
"Aqil taca zêrîn e ...Lê li ser serê hemî kesê nîne",
"Aqlê ji kîsî xelkê",
"Aqlê kurî hewa re firî",
"Aqlê kurî kavir hêla bizin birî",
"Aqlê kurî...Se pê birû",
"Aqlê kurî...Se pi birî",
"Aqlê te ev e...Ka yê çawebe yên pê te bikeve",
"Aşê dîna bê av digere",
"Av û av çû…",
"Av û avayî",
"Ava bîrê şêwr û tedbîrê",
"Ava cûyê ser erdê tenik de diqete",
"Ava royan disekine neyar nasekine",
"Ava ser berûyê de...Wey zavê li dilê xesûyê de",
"Ava xurtan ser ervazi ye",
"Ava xwestî...Naçe hestî",
"Avê bîne ji kenîyan...Jinê bîne ji eslîyan",
"Bar tên milê mov...Ne li hemdê mov",
"Barê giran hêviya Xwedê ve ye",
"Bawê baş bela serê kurê nebaş e",
"Bê aqilê bê mejî...Meaşê te kudeyek tijî...Bisekine an tu yê rêjî",
"Bê nan û xwê",
"Bê pîrê xwe...Neçe daweta mîrê xwe",
"Bê pîrekî neçe diwana mirekî...Da li serê te neyê teqdîrekî",
"Bêhna nêçîrvanî fire ye",
"Bêhna nêvçîkera fire ye",
"Bêhna Xwedê fire ye",
"Bêje ev nanê he ji sibe re...Nebêje ev karê he ji sibe re",
"Belaya ji cehaletê mezintir nîn e",
"Belayê Xwedê avis in",
"Berê gêrbirî ne hewce çi qulpan e",
"Berê giran li cihê xwe de baş e",
"Berê havînê bigre bavêje kadînê",
"Berxê nêr jibo kêr",
"Berxê nêr kuzgê de kifş e",
"Bêziravo emir dirêjo",
"Beziyê pê beziya bezî",
"Bi neyînê jar nebe...Bi heyînê har nebe",
"Bi pirsa...Diçe Qudsê",
"Bi xweziya dest nagihî keziya",
"Bibe tav nade hemuya",
"Biçe ser keniyê dê kenî biçikî",
"Bihar bi gulekê nayê",
"Bike tûr ... Da tu bikî ûr",
"Bila ev car jî wek hemî cara be",
"Bila mêrê min law be...Bila kirasê min caw be",
"Bila mov jina mêra be...Bila mov li ber beran be",
"Bila mov kuştiyê xweşmêra be...Bila mov ne girtiyê qelsemêra be",
"Bila nan mal be...Bila xwarin nan û av be",
"Bila pişta te li malê te be...Ne bila berê xelkê li malê te be",
"Bila rûyê te biêşî...Ne bila dilê te biêşî",
"Binive neyî rabe heyî...Binive heyî rabe neyî",
"Bira bira ye ...Bazar cuda ye",
"Bîra min sererd e...Av xwe li tê de nagire",
"Birçîyê mala xwe be...Ne têrxwerê mala xelkê be",
"Bişixule wek şêran...Bixwe wek mêran",
"Bizin bizin e dema mexel tê cihê xwe dixepîre",
"Bizin disekite jî qimçika xwe danane",
"Blûra li ber guhê gayî ye",
"Bo dînê xwe wek dînan be",
"Bostek teqsîrî gazek xusar jê çêdibe",
"Bostek teqsîrî heft gaz xusar jê çêdibe",
"Bûk li dilê zavî ye",
"Can pîr dibe dil pîr nabe",
"Carna nanê mov dibe bila serê mov",
"Cih ji ciha pîroztir e",
"Cih ji mirova teng nabe",
"Çar tiştê pîs hene lê ji wan pîstir jî hene...Kundî pîs e lê dewlemend bike hê pîstir e...Hesedî pîse lê alim bike hê pîstir e...Qehbî pîs e lê pîr bike hê pîstir e...Tirî pîs e lê feqîrê tir hê hê pîstir e...",
"Çav ji çavan fihê dike",
"Çavê kor hêstir jî jê bê baş e",
"Çavê reş ne hewceyê kilî ye",
"Çavek yê mov diçe...Mov destê xwe dide ber yê din",
"Çêlek avis be dê her bizê",
"Çêlekek rîxo garanekê diherimîne",
"Çevê kul hêstir jî jê bê baş e",
"Çi kirasê tu bidirî em ê li xwe bikin",
"Çiya ji cihê xwe diçe...Lê exlaq ji cihê xwe naçe",
"Çiyayê bilind bê berf nabe",
"Çîyayê nifs jî hewce yê bilinde û...yê bilind jî hewce yê nifs e",
"Çû şamê...Tibayê amê",
"Çûkik li hêgê de kifş dibe",
"Çûv çûvî nas dike",
"Dar ter diçevî",
"Dara hişk buyî ye feydê kezaxê nîn e",
"Dara sebrê gelek tehl e...Dema pel pêve tê gelek şirîn e",
"Dara ser xwe re nebire",
"Dara stûr bibe wê biqire",
"Darê bin xwe re nebire",
"Darê binî re nebire",
"Darika xweziya ber negirtiye",
"Daweta mîran e...Girê feqîran e",
"Dayîn zayîn e",
"Dê û weleda girt şer...Ji ya bê aqila ve rast e",
"Dêhl hat ba se hat ji Bexda",
"Dêhla rîxo seyê gurîx jê dernakeve",
"Delîlê bê delîla Xwedê ye",
"Delinga bizinê girt...Devê şiyarî berda",
"Dema îş dikeve ervazî...Sebir ser êgir dirazî",
"Dema ker dikeve xweyî li şeşan e",
"Dema pez dikeve...Kêr zehf lbin",
"Dema serkenî şêlo be...Dûvkenî ji xwe şêlo ye",
"Dema siûd hat serî...Bizire wek kerî...Dinya û alemê bêje...Işt û aferîn...",
"Dema te darek li seyê xwe da...Dê her herkes li seyê te bide",
"Dema te girt bernede...Dema te berda pê nekeve",
"Dema te karî yê xwe tu yê karî yê hemî kesê",
"Deng nekirin zêr e...Ji bilî namûsa vêre",
"Dera destê te biçigê...Lingê xwe jî pê bavêje",
"Dera jin xirab neke ew der ava ye",
"Deriyan dade ciranê xwe diz neke",
"Dermanê xwestinê dayîn e",
"Dest destî nas dike",
"Destê danê çav jê fihê dike",
"Destê me li kedê...Lingê me li hedê",
"Destê rehet ser zigê birçî ye",
"Destê tinê bila neçe ser xwarinê",
"Destê tinê pêjin jê nayê",
"Destê vale ne ehl e ne sehl e",
"Dev dixwe çav fihê dike",
"Dev emîn e...Zig xedar e",
"Devê bixwe birinc zerê...Divê li xwe bigre xincerê",
"Devê sîr nexwarî...Bêhn jî nayê",
"Devê xelkê ne kunê dîwaran e...Em lepek herî bigrînê",
"Devgê dixwûn...Devgê dirûn",
"Dew birê mastî ye",
"Dew xwazê kude şunve",
"Dew xwazê kude veşêr",
"Dewê ceribandî çêtir e ji mastê ne ceribandî",
"Dewleta ba bin re biçe ne dewlet e",
"Dewleta lezû bez: Rez û pez",
"Dews ya kerê ye...Fiil ya Periyê ye",
"Dibêje lê napêje",
"Dijûn şenê mitirban e",
"Dikare te bibe ser avê...Te bê av bîne",
"Dîkê çê li hêgê de bang dide",
"Dil dila dihebîne",
"Dil mêşa gû ye",
"Dil pîr nabe",
"Dilê nazik çi mirada naxwaze",
"Dilê nazik nagihî miraza xwe",
"Dilê yekê çû goştê kerê, got:...Guhê wê wek kêrvûşkan e",
"Dinê hemî neyarê kewê ye...Kew jî neyarê xwe ye",
"Dinê ne şêv û rojek e",
"Dînî nas bike hê libas",
"Dinya an sond e an şahid e",
"Dinya milkê dewrê ye",
"Dinya ne milkê kesê ye",
"Dira bide dest dirnasan",
"Dîtina çava qinyata dilan e",
"Dîwara ez ji te re dibêjim...Bûkê guhê xwe bidegê",
"Diya dizan du tira dike...Yekê ji tirsa yekê ji keyfa",
"Diz û malxwê bûn yek...Ga li rojnê re hewa êxistin",
"Diza ji diza dizî...Erd û esman lê daberizî",
"Dizê havîne zivistanê eşkere dibe",
"Dîzika kevano bişkêne bê deng e",
"Dostê bawî li xwe neke dawî",
"Dostê te şekir jî be hemuyê ne kirikîne",
"Du serî dîzikekê de nayê pehtin",
"Du serî naçe cihûrekê de",
"Dûr be ezîz be",
"Dûr e ne zor e",
"Dûr here...Nêzîk were",
"Dûvê dinê dirêj e",
"Dûvikê rovî...Şahdê rovî",
"Dûvikê seyî rast dibe lê ew rast nabe",
"Ecelê bizinê tê...Diçe nanê şivên dixwe",
"Ecelê mêriye tê...Çeng û perê wê tê",
"Em bêhna kebaba ve çûn...Em ser daxdana kera ve bûn",
"Em çûyîn geliyê dêra...Xwelî hilavêtin pê bêran...Hin jin çêtirin ji van mêran",
"Emrê borî feyde nake",
"Erzan kirê heban dir",
"Eslê jinê jin e",
"Ev hê lêlê ye hê lolo ma ye",
"Ev ker neyê vî barî ye",
"Evd dike tedbîr Xwedê dike teqdîr",
"Ev e milê min...Ew e darê te",
"Ew darê mov û xwe bike xwe re...Kes nikare ji mov re derêxe",
"Ew gewriya Xwedê kun kirî...Dê rizqê wê jî bide",
"Ew gotin e...Ne ew roj e",
"Ew keniya tu jî divexwî heqê te nine tu şêlo bikî",
"Ew ker baş e li biharê ket û têr xwar û nezirî",
"Ew war e ne ew bihar e",
"Ez çi dibêjim tembûra min çi lêdixe",
"Ez dibêjim ev e hirç...Tu dibêjî ev e dews",
"Ez dibêjim nêr e...Tu dibêji bidoşe",
"Ez hêdîka diçim bela digihî min...Ez lez diçim ez digihîm belayê",
"Ez nahêjim livek genim...Lê bi dinya û alemê dikenim",
"Ez ne diçûm geliykê...Te ez kirim seviyekê",
"Ferxikê şêrî şêr e",
"Ga bide gamiriyan...Jina bide jinmiriyan",
"Gavan hat zeviyê jin bezî teşiyê",
"Gerayî be zana be",
"Gêre li golika nabe",
"Girtiyê evdan her berdayî ye",
"Giya ser rayê xwe şîn dibe",
"Goşt bê hestî nabe",
"Goşt xweş e îyar mergê reş e",
"Goştê hemî teyrikan nayê xwarin",
"Got kerê: Mizgîn lite, cehşek yê te bû...Kerêgot: Barê min her li pişta min e",
"Got kewê: Tu ji kû hez dikî...Got: Erdê ez lê ferx",
"Got koro: Te çi divê...Got: Çavek rehnî û girara têr dûn",
"Got: Pîyana Miran li erdê ket...Got: şikest an ne şikest...Got: Şikest an neşikest bû deng û li dinê ket!",
"Gotê: Kurê te ji birça mir...Got: Ma heyî û min ne dayê",
"Gotin hêstirê: Navê bavê te çi ye?...Got: Navê diya min mehîn e.",
"Gotin kitikê gûyê te derman e. Ax rada ser",
"Gotina paşiyê li ya pêşiyê nede",
"Gozekê nede kuran da nebe didu",
"Gundek e...Gindurek e",
"Gundê bixweyî ne dûr e",
"Gurê betal çû kerê şixul xwar",
"Gur pakî ji baranê hebuya...Wê kumek ji xwe re çêkira",
"Han tu serî li berî bidî...Han tu berî li serî bidî",
"Hê çêlek nezayî golik çû ser serbanî",
"Hê tu li gon reşa neketî",
"Hêceta kurî v...Mewîj kirî",
"Heçî avrêj e ew dewrêj e",
"Heçî dizane jixwe dizane...Yê nizane baqê nîskê ye",
"Heçî guhê xwe nede mezinan...Pê ve tê du şaxê bizinan",
"Heçî heyran nes neke...Bila rengê hevalî feke",
"Heçî ji te dûr e...Ew mîr e",
"Heçî ne li malekê...Nizane hewalekê",
"Heçî neza dawetê xweş reqas e",
"Heçî ser û pê ne...Ew behra keçan û dê ne",
"Heçî zavayek heye wî kerek heye",
"Heft sal xelatî ne bila salekê neyartî",
"Hêlîna teyrê kor Xwedê çêdike",
"Hemeta xwe bike nêva te yê bikeve",
"Hemî dizê bêrîyekê ne",
"Hemî kera li wişkkê neajo",
"Hemî kes goşt xwerin lê gur bûye ecêb",
"Hemî teyrik hêjîra naxwe",
"Her dîna xwelî li serî mexîna",
"Her ervaziyekî nişûviyek li pê re tê",
"Her kes hostayê dîwarê xwe ye",
"Her lîsanekî mirovek e",
"Here nik wî kesî yê te bigirîne...Neçe nik wî kesê te bikenîne",
"Her rastî li her derê nayê gotin",
"Her serîyekê aqilek e",
"Her seyê bireyî tu bergê bavîjê...Ber dê êne bi zêran",
"Her teyrikek refa xwe re difire",
"Her tişt ji ziravî diqete însan ji stûrî diqete",
"Her tişta nêr ser ya mê ye...Lê axaftina mê ser ya nêr e",
"Here welatek nenas...Medhê xwe bike bê qîyas",
"Hesp tineyê afir çêker",
"Hesp tineyî zîn peyda kir",
"Hespê çê alifê wî zêde ye",
"Hêstira hina disekite...Seyê hina zexm dibe",
"Heta kefa destî reş nebe...Tama devî xweş nabe",
"Heta kurî mal kir qira mal bir",
"Heta mar xwe rast neke...Nika bikeve kunê de",
"Heta min xwe nas kir...Min emir li xwe xilas kir",
"Heta mirinê kirin e",
"Heta mirov heft kêl xwê hevalê xwe re nexwe wî nas nake",
"Heta mitirb birçî nebe...Bîra diholê nayê bîrê",
"Heta mov ser destê xwe rêve neçe...Mov qîmetê lingê xwe nizane",
"Heta nekeve ser destan...Nizane qîmetê lingan",
"Heta neyê serê mov nayê bîra mov",
"Heta rastî geriya...Virê cihê xwe girt",
"Heta tu birincê nekutî pap xwe jî bernade",
"Heta tu yekê nedî tu yê duduyan nestînî",
"Heta xirab nebe ava nabe",
"Hey gopal stûr e hidûdê te dûr e...Hey gopalê te zirav e hidûdê te av e",
"Hey hebe şil û mil e...Hey nîn e keser û kul e",
"Hey te bivê tu nas bikî spehiya...Nefeke balaviya feke ji xew rabûya",
"Hey te got û te kir tu şêr î...Hey te negot û te kir tu mêr î...Hey te got û nekir tu hevalê kêr î",
"Hey tu Sinemê nas nekî feke rengê birayî",
"Heyî be kurê seyî be",
"Hezar gotin ne bedelê kiryarekê de ye",
"Hezar şîret û nesîhet ...Naçe guhê mirovê bê dewlet",
"Hin hingiv dixwin...Mêş hinan ve dide",
"Hingî av di golan de dimîne genî dibe",
"Hingî pehîn li ziga diket digota:...Ax pişta mino!",
"Hingî ser dimîne qun ecêba dibîne",
"Hingî stûyê devê stûr dibe...Quna devê teng dibe",
"Hingî tu gû têkve bidî bêhnê jê tê",
"Hingî tu mûyekê ji berazî bikî xêr e",
"Hingî tu singekî bikutî ew ê çelteyekê pîveke",
"Hirç û govend...Rovî û seyran",
"Hirçê ji pûjanê nexweş bû...Pûjan çû devê kuna wê de heşîn bû",
"Holî çêdike baw dimire holî çêdike dê dimire",
"Holî hatiye wê holî biçe",
"Hosta necar...Binive wek her car...Heta sibehi...Xwedê yek delîl hezar...Xwedê xaliqê cebbar",
"Însan tovê mirine ye",
"Îro ronahî ye sibe tarî ye",
"Îşê li hêviya xelkê...Wey ava li kelikê",
"Îşê şevê kenê rojê lê tê",
"Îşê xwe bike esas...Da dilê te neke waswas",
"Ji Aqlê sivik barê giran çêdibe",
"Ji bangerî mezintir ser çûkê de nayê",
"Ji ber şirikê çû ber gurikê",
"Ji berfê spîtir nin e...Se û ker jî dirûn ser",
"Ji der ve Temer axa ye...Li malê Temo tiro ye",
"Ji dêrê jî bû û ji mizgeftê jî bû",
"Ji ewrê xurxuro û ji seyê hirhiro netirse",
"Ji gelikan gelek diçe...Ji hindikan hindik diçe",
"Ji her bê dînekê re bê îmanek lazim e",
"Ji her ewrî baran nabare",
"Ji hinan re behr e...Ji hinan re jehr e",
"Ji jina xwe hêcet bû: ...Tu ari bêjing dikî tu quna xwe dihêjînî",
"Ji me re kelem e...Ji xelkê re melhem e",
"Ji tena xwe avêt behran",
"Ji tira hatiye...Yê li vira biçe",
"Ji weliya dikeve xwelî...Ji xweliya dikeve welî",
"Ji wî bitirse yê ji Xwedê netirse",
"Ji xelkê re ga ye...ji xwe re golik e",
"Ji xwarinê re bist e ji kirinê re sist e",
"Ji xwedî esla bipirse...Ji bê esla bitirse",
"Ji ya dizan ve hemû kes diz in",
"Ji ya nêrekerî ve maker hûrî ye",
"Ji ya qelsemêra ve laşê xweşmêra naêşe",
"Ji zeviyê re lê hat...Cotyarî medhê xwe kir",
"Jin bûnn malxwê kehrik birîn berxe hêlan nebirî",
"Jin darê şikestî ye",
"jin hene jinikok hene",
"Jin kirasê mêri ye",
"Jin sitara mêran e",
"Jin û mal ne mêrû mal",
"Jin xweş jin e mal mezin e",
"Jina bîne ji kolanan...Neîne ji reqs û dîlanan",
"Jinê baş şîrê pişta mêran e...Jina nebaş derd û êşa giran e",
"Jinê bîne ji kura re...Da kur bigihî riha re",
"Jinê bîne ji kura re...Hê negihayî riha re",
"Jinê bivê mêr wezîr e bivê rezîl e",
"Jûvanan gû bixaran...Dê li dinê de gû nebûya",
"Karê bê xusar nabe",
"Karê gavanan siwariya keran e",
"Karê xwe li zerera xelkê de nebîne",
"Karê Xwedê dan û standin e",
"Kê şixulê xirab kir? -Yê heyrî.",
"  Keça bîne bila pîr be...Boriya here bila kûr be...Riya here bila dûr be",
"Keçik e, dev miçik e, piş kuçik e",
"Kenê bê aran...Tê ji kunên diwaran",
"Kengê bibar e hingê zivistan e",
"Ker çi dizane ji bêhna miskê",
"Ker ker e...Dera lê hilteqînê carek dî wê derê re naçe",
"Ker neyî kurtan çêkir",
"Ker zehf in lê nagihîn hev û bizirîn",
"Kera girê nede nik keran...Da jî negire tir û fisan",
"Kerê nebe cem mehîna...Da ne elime kulm û pehîna",
"Kerê nemire bihar e...Heta şîn bibe qîvar e",
"Kêrvuşk hingî dimîne qewzek zêde tê ber",
"Kes bi rih û şaşikan nabe mela",
"Kes nabêje mastê min tirş e",
"Kes nikare barê hêceta rake",
"Kes piştî miriya nemiriye",
"Kesê ketiya nîne",
"Kesê malê dinê xwe re nebiriye",
"Kesê mino destê mino ...Hespê mino lingê mino",
"Kesê nexwestî naçe dawetê",
"Kew zimanê kewê dizane",
"Kezeb gurê har e",
"Kêzika kendala, bû kevaniya mala",
"Kî nêrî bikuje kevil yê wî ye",
"Kî wefa ye...Ew bira ye",
"Kî zava ye ew birazava ye",
"Kirasê bê beden stûyê me de tînin",
"Kirin û gotin ji hev dûr in",
"Kitik ne li mal e...Navê mişk evdirehman e",
"Kûder xar e...Ewder war e",
"Kûçikê qenç li ber deriyê xweyê xwe ye",
"Kudika tijî li ya vale nede",
"Kûr, dûr, hûr bajo",
"Kur rakirin ser rana...Ji me standin nêvrana",
"Kurmê darê ne ji darê be...Fenabûna Darê wê tune be",
"Kurtanê kerê zêr be jî ker her ker e",
"Lawînî li lawa tê",
"Lêhatin ji jêhatinê çêtir e",
"Li her gundekî malekî ava bike",
"Li te xweş e...Li min bistuşeş e",
"Lîdan ya nêvçîkaran e",
"Lomanîyên dinê ji ezabê gorê nexweştir e",
"Ma dar ji ber tovilê xwe der e",
"Ma ga dike û ga dixwe",
"Ma ji xwe de kerê hirç xeniqandiye",
"Ma ka ne ya te ye...Ma kadîn jî ne ya te ye",
"Ma ka ya te ye...Ma kadin jî ya te ye",
"Ma kî diçe gora kê de",
"Mane tira kêça jî nema jê re",
"Ma sala xelayê serê min dûn daye",
"Ma Şam dûr e...Ma mişar jî dûr e",
"Ma tu li guhê gayî de yî",
"Ma tu yê dûnê xwe li serê xwe re dî!",
"  Ma vir kavirek e",
"Mak li hêlînê de şêr e",
"Maka dewlemendiyê çirçûki ye",
"Mala bê serî...Wey xaniyê bê derî",
"Mala kuran kenya zêran",
"Mala pîrê...Xweştir e Ji ya mîrê",
"Malê dinê ji dinê re baş e",
"Malê dinê qirêja desta ye",
"Malê Kironiyan talan kirin...Nûga mala xwe bar kirin",
"Malê nexwarî behra zaliman e",
"Malî ne ji kurê qenc re bihêle...Ne ji yê xirab re bihêle",
"Malxwê me bû Silo...Xwerê me bû çilo",
"Mamê keşe...Hêcet xweş e",
"Mar rast diçe kunê",
"Marga mêwê ye ne li revê ye ne li bezê ye",
"Marî ji pungê nexweş bû...Punk çû devê kona marî de heşin bû",
"Mastê xwe li heft sûka firotiye...Ma yê ji te fihê bike",
"Me keziyê xwe hemî ser xelkê kur kir...Kesê mûyek yê xwe ser me kur nekir",
"Mêr dimire jin har dibe...Jin dimire mêr jar dibe",
"Mêr lehî ye...Jin qapû ye",
"Mêr mirine zifto rabûne",
"Mêranî ji sê tişta re nîn e: av û agir û berf e",
"Merdê ji kîs xelkê",
"Merdînî ne ji heyînê ye ji hindikê ye",
"Mêrikê feqîr dema nanek xwar...an yê jinekê revîne an yê mêrekê kuje",
"Mêvan mêvanên Xwedê ne",
"Mêvan rizqê xwe ve tên",
"Mexelhatina gayî heqê gayî ye...Beza seyî ne heqê seyî ye",
"Mezin bibe pir jî, nede ser",
"Mezin kêlimî ... kiçik elimî",
"Mih û pepikê xwe bizin û pepikê xwe...Herkes mêvanê emelê xwe",
"Min çêl dayî te...Ma min fereşîn jî dayî te",
"Min çi çare ji keçeliya xwe re nedîtiye...heta ez ya te pirs bikim",
"Min dinya dût û vedût...Min nedît wey rez û cût",
"Min ew elimand dawetê êdî destê min nagire",
"Min ji te re got merheba...Te rût ser kurk û eba",
"Mirî ne melun be...Gor lî teng nabe",
"Mirin ne ji pîrî û canî ye",
"Mirîşk hêk dike...Birh li quna dik dibe",
"Mirov bizane wê kengê bimire...Wê tirba xwe hazir bike",
"Mirov di herfê Quranê de jî şaş dibe",
"Mirov diz be şêvê tarî zehf in",
"Mirov ji testika xwe têr nebe...Mirov ji testika xelkê têr nabe",
"Mirov mecbûr be goştê kewan jî dixwe",
"Mirov navê ji bilî kurê wî jî çêtir be",
"Mirov nikare kelika xwe bê tû ji wan biborîne...Nemaze du liv tû li tê de be",
"Mirov nikare ne pê te bê û ne pêşiya te biçe",
"Mirov seyî dide ser xatirê xweyî",
"Mirovê mov çiqas mov bikuje jî...Dê hestiyê mov her veşêre",
"Mirovê xerîb kor e",
"Mov çi qas aqil be têra mov nake",
"Nalbenda hespê xwe nal kir...Kêvjala lingê xwe raber kir",
"Nan û mast...Mast û mene",
"Nan xwerê min e...Şîretkarê xelkê ye",
"Nan xwerê xwe ye...Şîretkarê xelkê ye",
"Nana bide nanpêja...Bila nanek zêde be",
"Nanê genim li zigê hemî hesê de nasekine",
"Nanê Îsa dixwe...Selewata li ser Mûsa dide",
"Nanê mêran li mêran ker e",
"Nanê şewitî behra nanpêja ye",
"Nanê xwe bavêje ber tavê...Tu xwe rûne ber sihê",
"Nanê xwe ji berî dertîne",
"Navê betê ji dûr ve xweş e",
"Navê bivir ji bivir naçe",
"Ne cejn e sayran e...Ev çi reqs û dîlan e",
"Ne dêrekê xirab bike...Ne mizgeftekê ava bike",
"Ne ewrê xirxiro ne mêrê zirziro",
"Ne kerê min e...Ne gayê te ye",
"Ne şeytên bibîne ne lenetê lê bîne",
"Ne xwezika wî şêrî du rovî biçinê",
"Nefeke rengê mêrî û yê titinê",
"Nefs li hemî kesê...Libas ne li hemî kesê",
"Nesîb gêr kirin hemî kes revîn yê hevalê xwe...Aqil gêr kirin hemî revîn yê xwe",
"Neyarê aqil ji dostê bê aqil çêtir e",
"Neyarê te hin diştan ji dostên de digirin....Nexa zehf dosta negire",
"Nezanê ne guhdar derdê bê derman e",
"Nezanîn ne eyb e<brPirs nekirin eyb e",
"Nikare kerî didane kurtanî",
"Nişanê barînê ba ne...Nişanê mirinê ta ne",
"Nîv mela dîn der da...Niv dixtûra can der da",
"Pê nefsê xwe avêt hepsê",
"Pênç tiliyên destî yek ne wek yekî ne",
"Pêşiya ji paşiya re çi nehêliştiye",
"Peza paşiyê ava şêlo vedixwe",
"Piç û piç biçe ber kuç",
"Pîr bike...Jibîr neke",
"Pîra Şamê tibayê amê",
"Pîrê nezanî yê mêr ke...Deva mehr û heştêgê xwe kir",
"Pirsker be, da tu zana bî",
"Piştî tengiyê firehî ye",
"Pîvaz her pîvaz e çi ter çi hişk",
"Pola ji pola nagire",
"Qasê berika xwe gava xwe bavêje",
"Qeda li wê tiştê bikeve ...Ew tişta ne ser xweyê xwe ve be",
"Qedrê mov li destê mov de ye",
"Qelî ji kulhê çênabe",
"Qelî ji serê beytakê çênabe",
"Qenciyê li qenca bike...Xweyê neqenciyê yê her gihî ya xwe",
"Qirqir binbir e",
"Qûna elimî tiran...Narûne ser çi beran",
"Qunê pê min neyê bêhn ji te tê",
"Rastî şîrê Xwedê ye",
"Rastî tehl e",
"Rasto diristo...Xwehro şikesto",
"Reş û bi destê xwe an avê tu birî",
"Rih dibe bost...Neyar nabe dost",
"Rim dikarikê de nayê veşartin",
"Rizqê bê him him nabe",
"Rizqê gurî li quna şivanê pîs de ye",
"Rizqê haran ser dînan e",
"Rojek nêrekerî çêtir e ji bîst û pazdeh ên makerî",
"Rovî nedikarî biçe kunê...Hejiyek jî serê dûvê xwe ve kir",
"Rovîyê gerayî...Ji şêrê nivistî çêtir e",
"Rû ji rû fihê dike",
"Ruh ji tengî naçe",
"Rûniştin dê û bav e...Nabêje mirov rabe",
"Rûvî têr e...Tirî tirş e",
"Rûyê reş ne hewce teniyê ye",
"Sax dibe birîna şîr û tîran sax nabe birîna zimanan",
"Se direyî karwan dibore",
"Se direyi, karwan rêya xwe de diçe",
"Sê gidî hene li dinê...Mala xwe didane nik mala bawê jinê...Ber ervaziya vedixwe cigare û titinê...Rêya diçe tinê",
"Se goştê sê naxwe",
"Se se ye...Wextê hestiyekê dixwe...Hesabê paşiya xwe dike",
"Sê tişt hene dil êş: mişk û mirîşk û mêş",
"Sê tişt hene lezzet: pez û rezû hirmet",
"Sê tişt hene sarî: tirşik û mehîr û karî",
"Ser hebin behlingî wê her hebin",
"Ser hene, serê ser lê bisekine nîne",
"Serê ne êşî ne hewce çi şaşikan e",
"Sere tît û mît...Binve quna rût",
"Sergû ser sebana nakeve",
"Seyê bireyî geza nake",
"Seyê xurtî biçe nêçîrê...Ma dê çi nêçîrê bike",
"Silam li mihan e an li rihan e",
"Simbêl kitika ve jî tê",
"Sitilê got ez zêrîn im heskoyê got min binê te dîtiye",
"Sivikê malê...Kiçikê malê",
"Siwarê tinê tozê nake",
"Siwarê xelkê her peyar e",
"Sûjine çavê hevalê xwe re dibîne...Gêsinî li çavê xwe re nabîne",
"Şa nebe li malê me...Wê li te bê halê me",
"Şekir şirîn e...Welat şirîntir e",
"Şekir tehl e...Tu şirîn î",
"Şer jî ji betaliyê çêtir e",
"Şêr şêr e...Çi jin e...Çi mêr e",
"Şer û niv şer yek in",
"Şer û tir ne li mov e",
"Şer xweş e li şûvê...Ne qaqaşa li bênderê",
"Şerbikê kevin li yê nû neguhere",
"Şert ne tûz û bertûz e...Şert tertîb û rêz e",
"Şeytan mêrek zexm e",
"Şilî şahî ye",
"Şîn û şahî li ber deriyê hemû kesê ne",
"Şîrê hêsin heft sala hilpesîre ...Disa yê çi ser guhê gêsin",
"Şirê mirîşkê jê kêm bû",
"Şîrê mirîşkê...Veşîre ji xwuşkê",
"Şîrê qetlê li milê te...Rehma Xwedê li dilê te",
"Şixul şêr e...Dema te dest avêtê rûvî ye",
"Şixulkerê xwe be...Ezizê dilê xelkê be",
"Şûna ji kula bimire bila pê bimire",
"Şûr kalanê xwe nabire",
"Te got: Kerê mirî tiran nake",
"Tê sotin...Nayê gotin",
"Te xwe li salê girt...Xwe li mehê jî bigire",
"Teşk û meşkê heve girê nede",
"Teyr hemû goşt dixwin lê...Gur bextereş e",
"Teyrika witwitanî...Te çi ji halê vê dinyayê nezanî...Te mala xwe xirab kir...Te ya min li ser danî",
"Tinedîtiya ti nedît...dema dît xwe ve rût",
"Tifaq tifiqiye",
"Tîjikê marî jî mar e",
"Tijî sûkê qumaş e mela bê şaş e",
"Timaya dinyayê gû dide xweyê xwe",
"Timayî ji gûyê sê pîstir e",
"Tîra ne li min re...Li vî kendalê re",
"Tirs mergê rovî ye",
"Tîşkêwikê li ber mirîşkan rabe nabe ribat",
"Tişta çû nede dûv",
"Tişta girtî şîrî...Naberde pîrî",
"Tişta ne serve wey tişta ji derve",
"Tu biçî masî wê quna te şil bibe",
"Tu çi bikî karê...Ew dê ê xarê",
"Tu derbekî danî û tu zerbekî bixwû weneke",
"Tu geliyê kûr de razî...Tuyê xewnê xirab bibînî",
"Tu heta pariyê xwe necû naçe xar",
"Tu ji evdan natirsî ma tu ji Xwedê jî fihê nakî",
"Tu mehdika hinan bihêjînî...Hin ê jî mehdika te bihêjînin",
"Tu nebînî zehmetî...Tu yê nebînî nimetî",
"Tu nezanî...Çav bide cîranî",
"Tu seyî bi heft ava jî bişo se se ye",
"Tu yê rojekê kewekê bigirî",
"War ji xerîban ava nabe",
"War kor nabe lê dixinise",
"Wekî gû ye hingî tu têkve bidî bêhn jê tê",
"Wextê ker dikeve heriyê...Ji xweyî ferztir nîne",
"Wextê tu diçûya avê ez jûve dihatim",
"Wextê Xwedê da...Nabêje tu kurê kê yî",
"Xala rakir xweherzî...Mama winda kir birazî",
"Xanî dilop bike...Pêşiyê xweyî lê dihesî",
"Xeberên êvaran dikevin qolên dîwaran",
"Xem û xew birê hev in",
"Xêr xweyê xwe nas dike",
"Xêra bike bi destê rastê...Bila destê çepê lê nehesî",
"Xeta kûr li bin gayê pîr",
"Xew û kew des mov nakeve",
"Xeyalên aşvên her aş e",
"Xirab kirin rehet e ava kirin zehmet e",
"Xiyala aşvanî her aş e",
"Xulamên axa jî axa ne",
"Xunkar e ne bê kar e",
"Xurt dizane kêrvuşk nêr e an mê ye",
"Xwarin xweş e...Kirin mergê reş e",
"Xwedê berfê dide da dest û pê bicemide",
"Xwedê deriyekê bigire deh deriyan vedike",
"Xwedê dike mû jî naqetîne",
"Xwedê goştî dide guriyê bê didan",
"Xwedê gotiye: Ev agir e destê xwe ne êxe tê de",
"Xwedê gotiye: ji te hereket ji min bereket",
"Xwedê gotiye: Tu çi bixwazî ez ê wê bidim te",
"Xwehr rûne...Rast biştexile",
"Xwerê îso guriz e...Şalê îso qurmiz e",
"Xweyê keriyan...Çû nik xweyê keran...Ka piçe dûnê seran",
"Xweyê miriyan kor e",
"Xweyê sebrê...Bû mîrê Misrê",
"Xwezika wê pîrê...Bîr bên bîrê",
"Xwezî aqlê kurmancan ê paşiyê yê me bûya",
"Xwezî çêlikê guran bama...Ne biçûkê biran bama",
"Xwezî ez ne birayê kiçik bama...Bila ez mêlkoçek bama",
"Xwezî mirin hebûya pîrî nebûya",
"Xwîn nabe av",
"Ya borî borî ye, ya bê hê pêtir e",
"Ya dil dihebîne ew mehbûb e",
"Ya kesê kes dizane...Ya rêrê bivir û das dizane",
"Ya xelkê edet e ya me qebahet e",
"Yal tête dilan...Nayê milan",
"Yan mêr be mêrxas be...Yan tevir be das be...Yan bimire ji dinyayê xelas be",
"Yarê derewîn carekê dixwe firavîn",
"Yê bê hesab be yê bê hesab biçe",
"Yê binve razî ye yê ser nerazî ye",
"Yê dest bike bin guhê xwe ew dizane yê çi bibêje",
"Yê havînê bigirî, zivistanê jina wî ê bikene...Yê havînê bikene zivistanê jina wî ê bigirî",
"Yê kute biçe mazî...Na feke ser ervazî",
"Yê li hindikê qane nebe...Wê li rasta gelikê neyê",
"Yê neçûyî dawetê xweş reqqas e",
"Yekê çi behs nêv behsa neyî...Çû rût keniya gund de",
"Yekê ne dizanî mala dawetê...Dest avêt kefçikan û diçûyê",
"Yekê ne zar e ne ziman e...Yekê ne dîn e ne îman e",
"Yekê nezanî çi bike çû rût keniya gund de",
"Yekî dîn û yekî haş dan mû, mû neqeta",
"Zer ji mêzerê kêm bû",
"Zerikek virik xwe li ziga de digire...Qisetek xwe li zigan de nagire",
"Zigê têr hay ji yê birçî nîne",
"Ziman bê hestî ye",
"Zimanê dirêj ji xweyê xwe re bela ye",
"Zimanê jur re kêrek kuh têre",
"Zimanê leq û leq...Serê teq û teq",
"Zimanê mirov dibe bela serê mov",
"Zimanê xweş marî ji kunê dertîne",
"Zimano birîyo...Sero vehêsanoyo",
"Zirta bike belkî roja hewarê tu ne li mal buyî",
"Zivirina ji nêva rê jî kar e"]